### ISSUE TITLE
Highlighting Support

### ISSUE THREAD

**Issue by sgratzl** [deneb-viz/deneb#134]
AFAIK there are two modes for PowerBI how it handles incoming selections. First, via filtering and the other is by highlighting. 

It would be great if both would also be supported in deneb. Similar to what you are using for the `__status__` it could be another flag

**Comment by dm-p** [comment]
I've previously thought about highlight support, but it is a little more tricky to implement than cross-filtering ([ref](https://docs.microsoft.com/en-us/power-bi/developer/visuals/highlight?WT.mc_id=DP-MVP-5003712)).

The main challenge here is that cross-highlight can only be enabled in a visual's metadata for the capabilities exposed to the main Power BI window when the visual is added to the report (rather than the canvas). 

We are not able to turn this off from within a visual instance (like we can for other interactivity features) based on user preferences, as there is no API for it. It is assumed that if a visual author has enabled this capability then they will have coded the necessary logic to manage the highlight of data points.

Therefore cross-highlight will always be an option for a Deneb visual when editing interactions between other visuals in Power BI, irrespective of whether a creator wants it there or not. Feedback from user groups and webinars where we've presented Deneb is that this is not a particularly desirable outcome and users would prefer cross-filter only as an option. This viewpoint may well change as more users are exposed to Deneb in future so I'm keen to wait a bit longer and explore potential for a happy medium somewhere.

In terms of state management, Power BI sends across a complimentary array with the data view that denotes a highlight value for each column or measure. This is "more or less" binary for everything apart from numeric measures; in this case these may also be partial (or greater) values than the initial query result, rather than simply on/off (or `null` vs. `!null`) in the visuals API. So we may want to think about how this might look from an implementation perspective for a creator.

Have added this to the backlog for further consideration post-1.0/AppSource and request for further comments are welcome. Ideally we can find a good solution here. My initial thoughts are if we can gracefully handle the situation where a user doesn't want to manage this themselves then we have something similar to your suggestion to flag a row's 'highlight' status. We may wish to either create complimentary 'highlight' values for each numeric measure as well, so that we can have much more granular management over our visual's appearance. This gives us extra things to think about when handling features like #35 in a more automated way.

**Comment by PBI-David** [comment]
With ref to this quote:

>therefore cross-highlight will always be an option for a Deneb visual when editing interactions between other visuals in Power BI, irrespective of whether a creator wants it there or not. Feedback from user groups and webinars where we've presented Deneb is that this is not a particularly desirable outcome and users would prefer cross-filter only as an option. 

Can't users who do not want cross highlighting just disable it with the Edit Interactions functionality in PBI or have I misunderstood?

**Comment by dm-p** [comment]
They can certainly do this and would have to if we implement the feature.

**Comment by PBI-David** [comment]
Has any further thought been given to this? Cross highlighting is currently my only blocker preventing me from using Deneb in my reports. 

Regarding the implementation, you have said we currently receive a values array and we could augment this with a highlights array. The problem with this approach is that when cross highlighting occurs, the visual creator has to dim the colours of the values array and make the values in the highlights array the original colour. Is it an option to supply a lowlights array instead (the inverse of the highlights array). This way the visual creator could specify two marks in their config with a lowlights mark layered over the values mark. The values mark would be the standard colour they wish to show and the lowlights mark would be the muted transparent colour. Lowlights would be an exact copy of values but would only show when they array is actually passed to Deneb by PBI. 

I don't have a proper grasp of how things work under the covers so if this idea is nonsense then I will defer to the experts.

**Comment by dm-p** [comment]
I've put a lot of time into researching this but haven't been able to write-up, as I'm a bit short on free time at present. I will try to do so before I start work on the feature (likely in 1.2 or 1.3, depending on my bandwidth). 

In short, my initial thoughts were naive and if we introduce cross-highlight as a capability, existing users will need to explicitly change any visuals to cross-filter (unless they have the default interaction set this way) as there are no APIs to support this "migration". In terms of how this will work for existing users, I consider it a breaking change. 

Thanks for your suggestions - I will need to find some more time to look at them in detail and see if they are workable relative to my current notes. If these aren't able to mitigate my current findings I will hopefully have a strategy by the time 1.1 goes live and I can add some documentation for users to expect a breaking change by the time 1.2 or 1.3 becomes available so that people have had fair warning to prepare for the upcoming changes.

I estimate that 1.2 will be fully deployed through AppSource by March; I don't have an ETA for 1.3 but would likely be late April.

Either way, once we have a decent stab at a working feature underway you'd be able to use [an alpha build](https://deneb-viz.github.io/community/early-access) to verify and provide feedback before we submit to AppSource, should you wish to do so.

**Comment by dm-p** [comment]
Tentatively scheduling for 1.2; we'll at least get some of the groundwork done in this release if it proves to be too big and needs to be fully delivered in 1.3. [I've updated the changelog with a warning that it's coming up](https://deneb-viz.github.io/changelog).

**Comment by PBI-David** [comment]
Awesome 🥇

**Comment by dm-p** [comment]
Doing some work on this and I think I have a workable solution that will satisfy most users, but will have quirks.

### Things We Can't Change if We Enable the Feature (as we don't have APIs for anything else)

* As discussed, once we enable a particular custom visual to support cross highlight, this changes its behaviour.
* Typically Power BI will set its default interaction to cross-highlight and send the highlight values if another visual is clicked.
* Under if our author visual does not explicitly deal with these values, a visual will appear to do nothing, similar to our example from the post higher up:

  https://user-images.githubusercontent.com/10572054/139187761-53fdde9d-a4ba-4db6-b017-0d5dbb5bd23a.mp4

* This means that conventionally, we effectively force creators to handle highlights if we turn this on.

### How I Propose We Should Handle It

(...and basically because it's a bit tricky to explain: how I have it prototyped)

This is to ensure continuity for existing users as much as possible, particularly if they are not in a position to update their visual straight away. It may, however result in some slightly unexpected (but not world-ending behaviour if this change goes live).

This proposed approach puts a bit more onus on those who want to modify their specification for cross-highlighting, but as they need to do more work, this may be okay.

* We enable highlight support in the visual so that the capability is possible (as above section).

* Under **Vega > Power BI Interactivity** (in the editor's settings tab), we add a **Cross-Highlight** property, which is **OFF** by default (much like cross-filtering).

* This means that if a creator wishes to use cross-highlight, they need this property enabled **AND** the interaction in the visual header set to cross-highlight.

* With this property enabled, Deneb will pass in the values to the dataset as normal, and create additional versions for each measure with a `_highlight` suffix. For example, if your measure is `Mean Temperature`, you will have this field as normal for the 'pure' values, and a `Mean Temperature_highlight` that will have the pure value (if no highlight applied), or the highlight value (if another visual is clicked).

* Creators can then create a specification with handling for marks as appropriate, e.g.:

```json
{
  "data": {"name": "dataset"},
  "layer": [
    {
      "name": "Main Measure",
      "description": "Underlying semi-opaque mark, used to represent full value of measure (if cross-highlight is applied).",
      "mark": {
        "type": "bar",
        "tooltip": true,
        "opacity": 0.3
      },
      "encoding": {
        "x": {
          "field": "Mean Temperature",
          "type": "quantitative"
        }
      }
    },
    {
      "name": "Highlighted Values",
      "description": "Adapts to cross-highlight values (will be the same as main measure if not applied).",
      "mark": {
        "type": "bar",
        "tooltip": true
      },
      "encoding": {
        "x": {
          "field": "Mean Temperature_highlight",
          "type": "quantitative",
          "axis": {"title": null}
        },
        "opacity": {
          "condition": {
            "test": {
              "field": "__selected__",
              "equal": "off"
            },
            "value": 0.3
          },
          "value": 1
        }
      }
    }
  ],
  "encoding": {
    "y": {
      "field": "City",
      "type": "nominal",
      "axis": {"title": null}
    },
    "tooltip": [
      {"field": "City"},
      {"field": "Mean Temperature"},
      {
        "field": "Mean Temperature_highlight",
        "title": "Mean Temperature (Highlighted)",
        "format": "#0.00",
        "formatType": "pbiFormat"
      }
    ]
  }
}
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An example of how this looks when cross-filter is applied is as follows:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/10572054/152921754-b5d2b9b3-b0aa-4748-906c-479a69185af3.png)

* If this property is not set, but a creator has left the default interaction of cross-highlight enabled in the header - effectively meaning that there is no option to take-up cross-highlighting in Deneb, we will do the following internally:

    * **Not** create the additional highlight fields
    * Re-map the passed highlight values from Power BI to the regular field values

* This will (for the most part) give the appearance of the visual being cross-filtered, despite the header having the cross-highlight interaction set.

* If the Deneb visual is set to have a cross-filter interaction in the visual header, none of the above will matter; Power BI will not send highlights, so a creator doesn't need to handle them.

### Examples

To try and clarify this further, I've recorded the following short video. The salient points are these:

* We have a core bar chart with the same column and measure as our Deneb visuals at the bottom (more on those in a second)

* We have a core column chart with the same measure, but a different dimension as the Deneb visuals.

* We have 4 Deneb visuals at the bottom, with a simple bar chart specification. Each one has the following features:

    1. This is a standard bar chart template, with just the values. 
        * The proposed Cross-Highlight property is enabled
        * The visual interaction is set to cross-highlight
        * This case represents a user who has enabled both conditions for cross-highlight but has not actually implemented in the spec
    2. This is a bar chart, implemented as per the above JSON, i.e.: 
        * The proposed Cross-Highlight property is enabled,
        * The visual interaction is set to cross-highlight
        * The creator has built handling for both sets of values with appropriate marks
        * This should (for the most part) behave like the core visual above it
    3. This is the standard bar chart template, with just the values - as per case 1 - except:
         * The proposed Cross-Highlight property is disabled
         * The visual interaction is set to cross-highlight
         * This is the condition where Deneb will re-map highlight values to the 'pure' fields and represents the likely state where many users will not change the default interaction or apply their own handling of highlight values. This *should* (mostly) behave like...
    4. This is the standard chart template, with just the values - as per case 1 - except:
        * The visual interaction is set to cross-filter
        * In this case, Power BI does not send highlight values to Deneb, so we do not map them.

https://user-images.githubusercontent.com/10572054/152923688-c8031364-1b56-49da-b030-6c089aad9e4d.mp4

The video demonstrates how each visual responds for interactions with both core visuals.

----

I am hopeful that this is the best case scenario we can offer for the functionality that we currently have in the custom visuals SDK/APIs.

If there is no feedback to the contrary, this is how I will implement cross-highlight support in Deneb.

**Comment by PBI-David** [comment]
@dm-p  that seems very sensible and logical. Thank you for working on this.

**Comment by tomatminceddata** [comment]
@dm-p I like the solution a lot and agree with @PBI-David it seems logical.
From my experience, it is very valuable to have a deneb visual as a target for cross-highlighting that is in synch with other visuals. I consider it also not a great "change" if a content creator has to adapt an existing specification.

**Comment by PBI-David** [comment]
@dm-p I'm sure you have already seen this but wanted to double check before you commit to your implementation. Below is  adapted from the standard Vega-Lite example using click to cross highlight. It does this in a slightly different way to your sample JSON by using a filter transform instead. I'm not sure it changes anything but wanted to add it to the discussion.  

[Cross Highlight](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICAM2FksEfgCYA1lJnylxttuSY0oHEm0Q4Hg5h+6KqBIAC+EUqY2kiyEM6uaADaoFBIglAMgmpBGGw6EAAUIQwIlCFwAJSKIEgQ+pg0CH5hALpK2nA4cGr+UGyCpfKoSSo0EOqyUH5KynDZAJ41jc0grWFKEN1Q-otw2sme3kgI9SOgsie5UMJQNjW+gnBQ7pogmAvd+jhsNLLuSjgUzYyj+ZDOowAHmsIu0QMhtPd0ExvDUgf1QbIyP5oW9jDR5sp-J1ur10P1Bgh5BsQEw-v5kJC6XE0FYAAyREBLN5IMhkToUULk-L-cJKCkufzEdIMXIAYmUivCkVA0Vi8RcCEOIHxgkCBzeXhiWvJt3usKUCKRtNRgOBmOxb1xoHxhOJXR6rxAFKGYtp9LejOZZ3ZnO5oF5-L4Qu9IvcETaESAA)

**Comment by jrescalante** [comment]
I'm being using the cross filter for different scenarios, and this addition is in the same direction. I like it, whenever we are used to filter or highlight. Also, is just a little adjustment to do in the previous visuals created in Deneb.

**Comment by dm-p** [comment]
[I lost my changes just before I hit the Comment button and have had to re-type; hopefully I have everything as it was]

> I'm sure you have already seen this but wanted to double check before you commit to your implementation. Below is adapted from the standard Vega-Lite example using click to cross highlight. It does this in a slightly different way to your sample JSON by using a filter transform instead. I'm not sure it changes anything but wanted to add it to the discussion.
> 
> [Cross Highlight](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICAM2FksEfgCYA1lJnylxttuSY0oHEm0Q4Hg5h+6KqBIAC+EUqY2kiyEM6uaADaoFBIglAMgmpBGGw6EAAUIQwIlCFwAJSKIEgQ+pg0CH5hALpK2nA4cGr+UGyCpfKoSSo0EOqyUH5KynDZAJ41jc0grWFKEN1Q-otw2sme3kgI9SOgsie5UMJQNjW+gnBQ7pogmAvd+jhsNLLuSjgUzYyj+ZDOowAHmsIu0QMhtPd0ExvDUgf1QbIyP5oW9jDR5sp-J1ur10P1Bgh5BsQEw-v5kJC6XE0FYAAyREBLN5IMhkToUULk-L-cJKCkufzEdIMXIAYmUivCkVA0Vi8RcCEOIHxgkCBzeXhiWvJt3usKUCKRtNRgOBmOxb1xoHxhOJXR6rxAFKGYtp9LejOZZ3ZnO5oF5-L4Qu9IvcETaESAA)

@PBI-David - thanks for all the effort you're making to look into this. Cross-highlight and cross-filtering are events external to the visual and handled by the main Power BI window, so it's more about how we handle and expose the incoming data for the creator in their specifications.

The linked example is based around the signals that Vega(Lite) will expose internally based on those internal events. In our case, we're changing the dataset before it hits the Vega view, so the field values are changing externally rather than though events internal to the Vega view. It may be possible to adapt the `filter` transform approach for the dataset that we're proposing to build based on the external events from Power BI. 

My example above is probably not definitive and more to help illustrate how I *might* handle the new fields to achieve cross-highlight support for a specification; I look forward to seeing how creators may choose to implement for their visuals.

I think that as long as the proposed incoming dataset makes sense for creators, and we can handle specifications that don't want to go the extra mile in managing this, I think we're looking good. For such a flexible visual, it's not going to be 100% clean, but I want as little friction as possible for creators.

Thanks also to @tomatminceddata and @jrescalante for adding their thoughts too :)

**Comment by dm-p** [comment]
The first [1.2 alpha build](https://deneb.link/alpha-build) with cross-highlight support enabled is available for anyone interested in this feature and wants to test and provide feedback.

I'm still polishing the functionality and documentation for submission to AppSource, so we probably have a couple of weeks to make any fixes. **I strongly advise that if you have any thoughts on how this needs to work better, please provide them ASAP**, otherwise this is the implementation that will get submitted for approval. Alpha builds are not supported for production use, but I'm keen to hear about any issues you might find so that we can polish this up as best we can prior to submission (as it's a lengthy process to get fixes through).

[The version 1.2 staging area of the documentation site at deneb-viz.github.io](https://deneb-viz.github.io/next) is mostly up-to-date for all current features and fixes. I'd recommend starting with [the Change Log](https://deneb-viz.github.io/next/changelog), and then moving to the Cross-Highlighting documentation. I still need to update the inbuilt templates, but I'm optimistic that the documentation, plus information on this issue should be enough to get started with.

**Comment by PBI-David** [comment]
Top stuff @dm-p :clap:. This works perfectly for me.

**Comment by dm-p** [comment]
I'm closing this out now, as there's been no further feedback and I've just submitted 1.2 with this functionality. Rough guidelines from MS are 3-4 weeks for approval.

For anything new that comes up, we can track it as a separate issue.
