### ISSUE TITLE
Vega Lite Version

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#184]
Which version of Vega Lite is currently packaged with Deneb? I'm trying to create a _really_ simple grouped bar chart and getting schema validation errors. 

Here it is working perfectly in [Vega online:](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoAEIBVNCACCikABUAnjjiWrUTAx22Aajr1oARgAGEIBfBVMLdBslR2dLADE2ACc4KCQITB8-F1QAJhCg8MjLE1s43Ot3T0Fs3VyxAHYATmKQc1Lyp0qk1PTMuv9UMTCI9qiQAGEu+OjqryVferQ8poAWNo70adjuxJS0jKzFnJWCooBdcJBkZIBrSyYkZNs4WSg2ZRpZMjRQBz+IAAZjQ4IJlKULNcAB6AkFgiHoJb+JSYPboACOnlkmDoahopBA1wcAHkgUCIHAsppgaDwZYKkSlB9BCk4XTEfY9qEeUA)

![image](https://user-images.githubusercontent.com/86846675/148979835-c85cf35a-65f9-4968-b5ac-a3984d1d19dd.png)

However, the attached .pbix with same data and config gives me this error: <html>
Ln 4 | .encoding | should NOT have additional property: yOffset
[Deneb.zip](https://github.com/deneb-viz/deneb/files/7848151/Deneb.zip)

**Comment by dm-p** [comment]
It tells you on the landing page, e.g.:

![viz-landing-f43c8a2250e8ebce130825f4cfd2b8a4.png](https://user-images.githubusercontent.com/10572054/148994480-b5f47a04-6d68-48e0-8859-c760814ceea6.png)

The offset encoding channel was introduced in 5.2.0 of Vega-Lite, which was released after Deneb 1.0 got approved to AppSource. Deneb 1.1 has since been submitted and will contain Vega-Lite 5.2.0. I don't have an ETA for this, as it's entirely dependent on when MS can review and process.

If you want to use this now (or at least verify) you can install the [latest beta](https://deneb-viz.github.io/community/early-access), but bear in mind that this is an independent visual and not the certified version. Also note that alpha/beta builds are for evaluation purposes only and are not supported for production use.

**Comment by PBI-David** [comment]
D'oh - I looked everywhere and couldn't see the wood for the trees. Thanks @dm-p   - there is no rush.

**Comment by dm-p** [comment]
I concede that the landing page isn't much use once you've started creating. I'll add a task to 1.2 to list versions on the Settings pane so that it's easier to discover in this state also.

**Comment by dm-p** [comment]
Now I'm back at my desk, I'll also just mention that to mark this small, but incredibly useful addition to Vega-Lite, there will be a [template for the grouped bar chart](https://github.com/deneb-viz/deneb/blob/e0bcc4fea1f086a5b2825d2db6ecd0fdb4295590/src/templates/vegaLite/vlBarGrouped.ts) in 1.1:

![image](https://deneb-viz.github.io/assets/images/template-changes-4ccb1ca2aba56c194dc6f1cb23693ddb.png)
