### ISSUE TITLE
Tree Layout Issues

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#199]
I'm trying to create a tree layout in Deneb but nothing is rendering at all. 

Here are the very beginnings of a tree layout in the vega editor with everything but the basics stripped out. 

[Editor](https://vega.github.io/editor/#/url/vega/N4IgJghgLhIFwG1QDsIFsCm9zQgZwyhABoQBXAJwBttIYB6AMyogowDoArPAe2RJBQKEZHkY8KaeEkEBPAA5Y4IPEOgBLRrIEBrDNuXqwA+awzIoAaX3ZTbCyAC+xUFAVLBbLKUxQAFjzGylBG2qR46gBeSggATAAM8cQJ8QC64Rh2GnzwjBBUBKT40iBhIAAeAmCZ-gIAxn7qVGD2IKmO7ekgaKw6eNKu7th4smgARjw0pIwUPFJwoHSwyksERM4g5nWBSqDmUBgU8KAR0ccgAG75ZEoAjIkbqrN651dUN9gAxIw-Thtk8jouwq50Y6gwzWwlQ2BlAYIhQVKTmmTRoC0u1w8bGMjlxHUcQA)

When I try to recreate in Deneb, I get a blank canvas with no warnings or errors. To recreate, I downloaded the JSON from here: https://vega.github.io/editor/data/flare.json, imported into PBI using PowerQuery and added all the fields to the Deneb visual well. Then I just updated the references to use "dataset".

Power BI file here:

[Tree Test.zip](https://github.com/deneb-viz/deneb/files/8008508/Tree.Test.zip)

Full Deneb code is:

`{
  "data": [
    {
      "name": "dataset",
      "transform": [
        {
          "type": "stratify",
          "key": "id",
          "parentKey": "parent"
        },
        {
          "type": "tree",
          "method": "tidy",
          "size": [200, 200],
          "separation": false,
          "as": [
            "y",
            "x",
            "depth",
            "children"
          ]
        }
      ]
    }
  ],
  "marks": [
    {
      "type": "symbol",
      "from": {"data": "dataset"},
      "encode": {
        "enter": {
          "size": {"value": 100},
          "stroke": {"value": "#fff"}
        },
        "update": {
          "x": {"field": "x"},
          "y": {"field": "y"},
          "fill": {"value": "red"}
        }
      }
    }
  ]
}`

**Comment by dm-p** [comment]
Thanks for providing all the details - it makes it much easier to diagnose :)

The root of the issue is that Power BI is summarising or aggregating your data, whereas the Vega editor is not. This is one of the things to consider with Power BI & Deneb - you will need the grain of your visual dataset to match the desired grain of the source data that you generate your spec with.

Converting your Deneb visual to a table, the dataset looks as follows:

![image](https://user-images.githubusercontent.com/10572054/152667368-877b8a41-62a6-4813-95ac-7ac7c3acec1d.png)

This is because the Summarization is set to **Sum** for the `id`, `parent` and `size` fields in the data model, and adding them to the Deneb (or a table) visual will automatically aggregate the data.

In order to match the behaviour of Vega in the editor, you need to make Power BI not aggregate the fields. This can be done by one of the following:

1. Changing the default aggregation for all fields to **Don't summarize**, e.g.:

    ![image](https://user-images.githubusercontent.com/10572054/152667448-1d208f79-ac7b-4ddb-bfdc-bad994c6b20a.png)

2. When adding the fields to the Deneb dataset, change their aggregation type to **Don't summarize** in the data role, e.g.:

    ![image](https://user-images.githubusercontent.com/10572054/152667463-14e3f2e8-c79c-45c0-b562-7942e80bde85.png)

You ideally want your visual dataset to look like this (rather than above, which is aggregated; notice that there are no totals now):

![image](https://user-images.githubusercontent.com/10572054/152667481-667e9d88-95db-4591-ac73-02b3275aaf8a.png)

By taking your visual as-is and changing the numeric fields to **Don't summarize**, I get this:

![image](https://user-images.githubusercontent.com/10572054/152667522-61611579-5f21-4248-86af-e8da3cf50791.png)

...which should match the Vega editor:

![image](https://user-images.githubusercontent.com/10572054/152667538-d5f85f9a-805a-4017-ac30-a183197b1629.png)

[I wrote this article a while back, to help with understanding how Power BI aggregates data](https://coacervo.co/violin-plot-sampling), and was geared towards visuals like the Violin Plot, R/Python & Charticulator. It pre-dates Deneb, but the concept is the same. Hopefully this helps clarify how the data needs to look to Deneb in these situations also. 

The advice I generally give folks with visuals like this is to check how it looks as a table first, to be sure that Power BI isn't aggregating it to a grain that you're not expecting - we also [lay this out at a high-level in the doc](https://deneb-viz.github.io/dataset#grain--row-context), but there's also a page [in the sample workbook](https://appsource.powerbi.com/deneb.deneb7E15AEF80B9E4D4F8E12924291ECE89A.1.1.0.0.pbix) dedicated to this concept:

![image](https://user-images.githubusercontent.com/10572054/152667661-71cde9c3-2013-4e44-a2ef-f33a18a156de.png)


Hopefully over time we'll be able to add more debugging options such as how datasets look, and the Vega logging (much like Vega editor) does, and this should improve productivity with these kinds of things. In the meantime, hopefully this gets you moving with your current project.

**Comment by PBI-David** [comment]
Thanks Daniel. When switching datasets, I completely forgot to check my data in a table. I'm going to go and punch myself in the face now :laughing:.
