### ISSUE TITLE
Autosizing a faceted or concatenated chart

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#203]
I think this may be a Vega-Lite limitation rather than Deneb but wanted to double check. Using a single chart, it is very easy to make a chart autosize to fill its container without worrying about specifying width, height or step size. However, this falls apart completely when using facets or when you hconcat/vconcat charts together. Attached is a sample .pbix. The visual with a single chart can be resized and the chart will fill the available space. However, the visual with a hconcat of two charts is fixed and won't adjust to the resize. When using row or column faceting, I have the same issue of autosize not working but see different behaviour whereby the chart scales but will never accommodate both charts.

When faceting or concatenating charts, do we have to provide fixed dimensions or step sizes and is this a Deneb or Vega-Lite limitation? Thanks in advance. 
[Autosize.zip](https://github.com/deneb-viz/deneb/files/8090376/Autosize.zip)

**Comment by dm-p** [comment]
Yes, these are both features of Vega-Lite and need to be raised there for consideration. There is already an issue for auto-sizing facets ([VL 5219](https://github.com/vega/vega-lite/issues/5219)) that's been open for a while. It might be a tough nut to crack, and I have had a look at seeing if I can help pick it up, but I need to start smaller if I can get to a position where I could help contribute to Vega-Lite. Building Deneb has taught me that I'm perhaps not quite ready enough to do anything big at the language level.

Depending on your requirements with faceting (particularly if you don't need axes and title, but more of a layout), you can creatively use `xOffset` and `yOffset` within a plot to make it fit.

With concatenation - I'm not sure how this could easily be streamlined, as you might often want plots to use different proportions of the overall view and not just equal-sized plots, e.g.:

![image](https://user-images.githubusercontent.com/10572054/154551500-3312d4d2-3d7f-496d-a23e-443637970b6a.png)

This example is 2 x `vconcat` and 2 x `hconcat` in each. I use a combination of step/width and height for the heatmap, and manual width or height, depending on the bar or column plot. In a case like this, it could be handy to specify % of the view rather than an explicit pixel value, but I think that someone in the Vega-Lite team may be better to advise if this is a sensible proposal for the language. I think I might raise this use case as something to be considered.
