### ISSUE TITLE
Months in chronological order

### ISSUE THREAD

**Issue by AmaralCamila** [deneb-viz/deneb#204]
I'm not able to put the months in chronological order.

The column used was Month-Name, and this column is already being sorted by "Month number"

![image](https://user-images.githubusercontent.com/90918857/154872596-d3b734ab-269c-44ff-a03c-94986f9c3fb7.png)

**Comment by dm-p** [comment]
As per details on [Deneb's support page](https://deneb-viz.github.io/community/support#getting-support), the GitHub repo is not the best place to get specific assistance with the languages due to the very low volume of traffic and my need to focus on bugs and feature requests. I'd recommend referring to the links on that page for a wider audience that can probably help you more quickly in future.

For your question, please refer to [Vega-Lite's sorting documentation](https://vega.github.io/vega-lite/docs/sort.html). Here's a couple of possibilities:

* Add your month number column to the dataset and sort by that, e.g.:

  ![image](https://user-images.githubusercontent.com/10572054/154872995-234cf569-0c5e-492c-8919-0a2f09c2326b.png)

  ````json
     "y": {
      "field": "Month",
      "type": "ordinal",
      "sort": {"field": "Month Number"}
    },
  ````
 
* Specify manual sort order using field values, e.g.:

 ![image](https://user-images.githubusercontent.com/10572054/154873121-90317cb8-8ea7-492b-aae9-ce0a637c8e78.png)

  ````json
    "y": {
      "field": "Month",
      "type": "ordinal",
      "sort": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Sep", "Oct", "Nov", "Dec"]
    },
  ````

* Add a date field and use the `ordinal` type and the month [Time Unit](https://vega.github.io/vega-lite/docs/timeunit.html) of the date, e.g.:

  ![image](https://user-images.githubusercontent.com/10572054/154873366-6eb0bd4f-9dad-4506-acdf-d37a4b9c6afa.png)

  ````json
    "y": {
      "field": "Date",
      "type": "ordinal",
      "timeUnit": "month"
    },
  ````
