### ISSUE TITLE
param slider outside of visual

### ISSUE THREAD

**Issue by Seebaer1986** [deneb-viz/deneb#208]
I am having issues with params in Deneb.

The following example will generate a chart with a slider. 
```
{
  "data": {"values": [{"x": 50, "c": 1}, {"x": 250, "c": 2}]},   
  "params": [
    { "name": "max_x_axis", "value": 500,
      "bind": {"input": "range", "min": 1, "max": 500, "step": 10}}
  ],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "x", 
      "type": "quantitative", 
      "scale": {
        "domain": [0,{"expr": "max_x_axis"}]
      }
    },
    "color": {"field": "c", "type": "ordinal"}
  }
}
```
In the deneb preview, you can already see, that this slider is outside of the visuals bounds:
![image](https://user-images.githubusercontent.com/22417079/156005929-71ea7915-1f7a-42e5-95f8-29571586511c.png)

And indeed, when you look at the visual, you will need to use the scrollbar to get to the slider:
![image](https://user-images.githubusercontent.com/22417079/156006064-073a254c-86bd-462c-8d29-ec5b61467986.png)

[Example in Vega-Lite Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUAHvAKwAMANCAMbwCMAvuYfAExmU1wv0C6jIABwgAnCAFsccfCAB24jPBBiIBAPpqVASxyVk6BXDIUQAI00yw8UOYFooi0TIDmCymPN03KkqWNYoGAJ0pPS8XsIA1oomIiCUGDJUAPZg5k5WIEQIIABmmhgolnCZcSBQAJ4CBiAAjmgQMlCaME2IriBYVKgGoGBJyh5SFKAYBALCispqGgTaILyhHEkoSRPZeQVF1KUVVYqrqXIo86FAA)

**Comment by dm-p** [comment]
Hi, and thanks for your question. Vega views are typically a known height and/or width. Due to the fact that Power BI visuals can be flexible height and width, the Vega view is synced to these dimensions if you're not manually specifying width and/or height.

If you want a parameter to appear within the bound of the visual, I'd recommend that you manually set the `height` in the top-level of the specification as necessary, e.g.:

```json
{
  "height": 300,
  "data": {"values": [{"x": 50, "c": 1}, {"x": 250, "c": 2}]},   
  "params": [
    { "name": "max_x_axis", "value": 500,
      "bind": {"input": "range", "min": 1, "max": 500, "step": 10}}
  ],
  "mark": "bar",
  "encoding": {
    "x": {
      "field": "x", 
      "type": "quantitative", 
      "scale": {
        "domain": [0,{"expr": "max_x_axis"}]
      }
    },
    "color": {"field": "c", "type": "ordinal"}
  }
}
```
![image](https://user-images.githubusercontent.com/10572054/156044031-cb32020f-6963-4ea7-8357-95fd34c4a7ca.png)

Omitting the `width` will ensure that this is still automatically assigned but you can then tailor the height as necessary if you need to add more parameters,

**Comment by dm-p** [comment]
As there's been no further feedback on the provided response for a couple of weeks I'm assuming that this resolves the issue, so am closing to ensure that the backlog is up to date. If there are further questions, then this can be re-opened or a new issue raised as applicable.
