### ISSUE TITLE
Support supportsMultiVisualSelection 

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#213]
I'd like to request an enhancement to support: [supportsMultiVisualSelection ](https://docs.microsoft.com/en-us/power-bi/developer/visuals/supportsmultivisualselection-feature). I have raised a similar request against Charticulator here (in case there is anything you can reuse from their solution): https://github.com/microsoft/charticulator/issues/950.

I didn't realise this was missing until today when I did a demo and absent mindedly tried to select multiple data points across visuals.

**Comment by dm-p** [comment]
Unfortunately, doesn't look like it's a case of just switching it on - doing this will work for outbound multi-select, e.g. choose data point in Deneb visual and then select a data point in a core visual, but not the other way around (or selecting across multiple Deneb visuals).

The developer doc doesn't really go into further details about what to expect in the selection state for this scenario, so this will probably require some further analysis of what the main window sends in so we can resolve it properly vs. what we know about the current visual's selection (and then maybe some recommendations to MS to improve the doc if we find anything useful out).

It could of course also be how we set the `__selected__` value internally, but there's not much to go on without having to debug what the main window sends in these events and working out how to set selection state internally.

**Comment by PBI-David** [comment]
That sounds complicated and I'm sorry I can't help solve it. I did have a test with xViz variance chart and they seem to support it so it seems like there is a way but I have no idea how difficult the implementation is. This isn't a huge deal for me but it would definitely be nice to have tighter PBI integration.

**Comment by dm-p** [comment]
As do I - we'll figure it out :) 

Probably something simple, but needs a bit more time to work out (particularly as I'm finalising 1.2)

**Comment by zBritva** [comment]
If the visual already supports multiselect inside itself, switching should be enough.

Otherwise, you need to support second parameter 'multiSelect' of interface:

```
interface ISelectionManager {
    // ...
    select(selectionId: ISelectionId | ISelectionId[], multiSelect?: boolean): IPromise<ISelectionId[]>;
    // ...
}
```

Usually, you need pass there the `ctrlKey` value from mouse event.

**Comment by dm-p** [comment]
That's a good point, @zBritva - and one I assumed we were doing already... but having re-visited the code it would seem that I'm not, so I really appreciate the reminder :)

As we're having to create fields that flag selection state of a data point for the Vega dataset, we're currently listening for the ctrl key and using that to either reset or merge the current selectors rather than using the `multiSelect` parameter in the `selectionManager`. 

It may be a case of just needing to pass in the `multiSelect` flag for any `select()` calls, but as there's a lot of testing required around this and I'm almost ready to submit 1.2, I may keep it where it is on the backlog.

**Comment by dm-p** [comment]
Out of interest I just did this, and it works for external visuals, but then breaks 'internal' multi-select so there's definitely more work required to ensure we're handling this properly.

**Comment by dm-p** [comment]
I've re-approached Deneb's internal selection APIs and have managed to align it more with @zBritva's suggestion and like how it should be implemented for conventional visuals. This has the desired effect of given the `selectionManager` more work to do (rather than trying to manage too much state internally) and this means that multi-visual selection state is handled by the main window, as it really should be. Initial tests in my checkout are encouraging:

![Multi-Multi-Select](https://user-images.githubusercontent.com/10572054/157783998-462dc685-9ead-4912-945b-940ecc1492f6.gif)

This fix causes a regression in the restoration of selection state from bookmarks, so I will need to fix that and re-test all my current examples, to ensure that they work as expected. Because of this, I'm not comfortable shipping it in this state, and will dedicate some more time in 1.3. This feature will therefore likely appear in the first alpha build of 1.3 so that anyone who wants to test from their end can help me confirm it's working correctly. Will post a follow-up when it's ready (as I'm diverting to 1.2 packaging and submission for the next available chunk of free time).

**Comment by dm-p** [comment]
Initial functionality introduced in 1.3's first alpha build. If there are any further issues, please create a new issue with the prefix `[1.3 Alpha Testing]` and I'll flag for follow-up.
