### ISSUE TITLE
Please delete

### ISSUE THREAD

**Issue by steve257** [deneb-viz/deneb#247]

**Comment by dm-p** [comment]
I'll delete as requested, but as I got the original content via my notifications (and hopefully you may get this before I delete the issue), [you can fold/unfold code at the appropriate location using the keyboard](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts#folding). Where `0` is specified, use the `0` key along the top of your keyboard rather than the numpad.

Note that I am looking to replace the editor in later releases, so this functionality will likely change its key binding but still remain when I do. I will add more detailed documentation will all known editor shortcuts when this happens.

**Comment by PBI-David** [comment]
Nice to know. If you change the binding in future, consider the +/- keys on the numpad.

**Comment by dm-p** [comment]
Numpad +/- are currently reserved for the [zoom controls in the Debug Pane](https://deneb-viz.github.io/next/keyboard#debug-pane). 

We have to also consider avoiding breaking any main window hotkeys, or the browser (if editing in the Service). As to whether we can get a better editor will be dependent on whether I can get some changes approved with the visuals SDK; if not, we will have to stick with Ace Editor and its key mappings.
