### ISSUE TITLE
null Dates Causing Infinite Render Loop

### ISSUE THREAD

**Issue by hcoohb** [deneb-viz/deneb#259]
When one want to use a date field which has some blank values, Deneb crashes when clicking on the "create". It actually freeze the whole PBI instance and we have to hard kill it.

Easiest way to recreate:
1. manually create a table like so:
![image](https://user-images.githubusercontent.com/12975783/181670272-8edf85aa-b6de-4428-a58f-b0ff8c93df30.png)
2. create deneb chart with the date non summurized and Value as average:
![image](https://user-images.githubusercontent.com/12975783/181670552-0a62186f-ba7a-43b6-a459-4ea4fb426062.png)

Interestingly, if we convert the date to a "whole number", then the chart can be created with no pb:
![image](https://user-images.githubusercontent.com/12975783/181670676-b70b4cbd-0aa9-4a4d-97ee-6a56d9d71d13.png)
And if we convert back to date, the chart update with:
![image](https://user-images.githubusercontent.com/12975783/181670824-c850492f-5dc2-4598-8d32-fb8a34dbb84a.png)
But if we try to edit, full freeze of PBI.

I am not sure if it comes from vega or deneb, but maybe that still shouldn't crash the whole PBI..
Shouldn't a null date be considered as a "blank" for the category?

It will happen also if we try to use the date from a date_table and value from a fact table and if the date table does not have all available dates from the fact table.... which is pretty common in the reports I have inherited unfortunately...

deneb: 1.3.0
PBI: 2.107.841.0 64-bit (July 2022)

**Comment by dm-p** [comment]
Thanks for raising - I guess this is not going to be a typical use case, as the Date table should cover all dates available (as you've observed). From a dimensional modelling perspective, you'd typically join to an 'invalid date' record in the Date table to avoid these situations, but Power BI is more forgiving here with how it handles these cases.

This is a tricky one to debug, due to how it's breaking the main thread. The root cause appears to be that the `null` date (which would only be displayed as `'(blank)'` if you're applying [Power BI-style formatting](https://deneb-viz.github.io/next/formatting#power-bi-custom-formatter) to the column) is causing an issue with the memoization of the `<VisualRender/>` component, [specifically when previous and current datasets are compared](https://github.com/deneb-viz/deneb/blob/2f378ccf6917d08329d7587b83eeff1ffdd79478/src/components/VisualRender.tsx#L63).

What this means is that Deneb will check each time a change occurs to see if anything that _should_ cause a re-render of the Vega view will make it do so. Otherwise, there's no point re-rendering it as this has a performance cost. What is odd here, is that the incoming and existing data streams are the same, but it's getting stuck in an infinite loop.

If I inspect these objects manually (or even using a diff tool), there are no discernible changes to them, so this suggests an issue in the equivalency check (which can be tricky with deep objects).

We're using [Vega-Lite's `deepEqual` method](https://github.com/vega/vega-lite/blob/next/src/util.ts#L8) for this check. It _might_ be making some concessions for the sake of performance, and as Deneb's dataset is more complex that a typical Vega-Lite dataset object, we might be causing some fringe issues.

I have already found a suitable alternative and have this now working in my dev branch, and will add to v1.4. I'll have a new alpha build available shortly that you can use to verify the issue is resolved for you.

**Comment by dm-p** [comment]
A (hopeful) fix can be tested in the [latest alpha build](https://github.com/deneb-viz/deneb/releases/tag/alpha). If this looks good to you, I'll make sure it's included when 1.4 is submitted.

**Comment by hcoohb** [comment]
Thanks for the detailed explanation.
But I have to say it is pretty impressive that you could investigate and fix in a about as much time it took me just to report the issue!!
Thanks a lot!

Yes, all reports I just tested with the latest beta worked perfectly where deneb 1.3.0 would fail.

**Comment by dm-p** [comment]
I can't promise that they'll all get found and fixed so quickly, but I happened to be at my desk when the notification came in, and it looked bad enough to try and sort out ASAP so it can go into the next version. Coupled with your detailed reproduction steps, it made it more straightforward to find where it might have been going wrong rather than having to guess. Thanks very much for being so thorough on the detail - it really, really helps 👍

Glad to hear this one works for you too - as the AppSource submission process can be lengthy, I don't have an ETA as to when the certified version will be updated, but it will be submitted for validation soon (probably in the next couple of weeks).
