### ISSUE TITLE
Shortcuts righ ALT+F and right ALT+N should not work

### ISSUE THREAD

**Issue by lukasheinz92** [deneb-viz/deneb#262]
Hello, I use czech keyboard layout and if I press right ALT+F to insert `[` or right ALT+N to insert `}` then it opens the same windows as shortcuts CTRL+ALT+F or CTRL+ALT+N respectively. Please change the behavior so only shortucts with CTRL will be used.

**Comment by dm-p** [comment]
Thanks very much for letting me know, and that must be frustrating for you - very sorry about that.

This seems to be an odd issue, as the shortcuts are specifically bound to [Ctrl + Alt + [key]](https://github.com/deneb-viz/deneb/blob/4f0615e8848602af783fd169ad8b3cbb07ca11e0/config/deneb-config.json#L64-L71). I can confirm that these combinations do not trigger the dialogs on my keyboard layout (NZ), but we don't have any alt-characters tied to letters.

I'll have to do some research on the Czech layout and use of the right-alt key with respect to the library we're using to manage hotkey assignment, but I'll certainly see what I can do to sort it out.

**Comment by dm-p** [comment]
I've upgraded the keyboard library in the 1.6 branch and initial tests using a Czech layout look encouraging. This should hopefully be resolved in 1.6 when that's ready to submit.

**Comment by dm-p** [comment]
This is now available to test in the 1.6 alpha build. [Please refer to this blog post](https://coacervo.co/deneb_alpha_1_6) for an overview of the release contents, as well as links to the change log on the documentation site and how you can assist with testing and validating 1.6 if you are able.

It will be incredibly useful if you can confirm that this issue is resolved from your end, or if anything is outstanding to ensure it is completed. If I don't receive any further feedback, I'll close this off when 1.6 gets submitted to AppSource. Thanks once again for raising the issue and for using Deneb :)

**Comment by lukasheinz92** [comment]
I can confirm that it is fixed now, thank you.

**Comment by lukasheinz92** [comment]
I can confirm that it is fixed now, thank you.
