### ISSUE TITLE
Problem with accessing a single item in a dataset

### ISSUE THREAD

**Issue by avatorl** [deneb-viz/deneb#268]
It works well in a browser, but Deneb visual returns error

`Cannot read properties of null (reading 'marktype')`

data() function is being used in the following format to access a single item in a dataset

`{"signal": "data('dataset')[0]['Max']"}`
or
`{"signal": "data('dataset')[0].Max"}`

**Comment by dm-p** [comment]
As a workaround, you may be able to set the log level to _None_ in the Logs pane in the debug area'. I appreciate that this is not ideal.

I have a sneaking suspicion that you've come across #233, which I haven't been reliably able to reproduce, but will be trying to address in v2. I'll keep this open as a bug for now though so that we can track it and should be a good candidate for verifying when v2 builds become available - although I don't have an ETA for v2 yet.

I believe the root cause is that the UI is too tightly bound to the Vega logging and there are also some timing issues in how this is bound to the Vega view. Because the debug pane wasn't implemented until v1.3, the error output was being logged in the space occupied by the render output so that users at least had a clue that something was wrong, until the additional debugging features could be implemented. However, the binding between render output and log output (particularly with errors) remains in-place currently.

In terms of what v2 will do to address this, the rendering workflow is being redesigned to reduce unnecessary calls to the Vega view and we should only get one full render per spec update. The logs will also no longer be tied to the render output.

**Comment by dm-p** [comment]
I believe that the changes in 1.5.1 will resolve this, but please re-open with a sample spec if not and I will investigate further (and hopefully fix) in 1.6
