### ISSUE TITLE
Dataset losing rows

### ISSUE THREAD

**Issue by gdeckler** [deneb-viz/deneb#271]
Noticed this working with the DS - Penguins dataset. If you only include Island, Species, Beak Depth (mm) and Body Mass (g) in your Deneb visual rows are dropped from the dataset available to Vega/Vega-Lite. For example, there are 2 penguins on the island of Dream that are species Adelie with a Body Mass (g) of 3400 and a Beak Depth (mm) of 17.1. Only 1 of these rows is available in Deneb visual, the other duplicate row is dropped. This seems very reminiscent of the behavior of Python and R visuals that essentially de-duplicate rows. Is this intended behavior, something that is out of your control or ? In this circumstance this can be avoided by including Index within the visual but wanted to check.

**Comment by dm-p** [comment]
Hi Greg - yes, this is due to how Power BI aggregates to distinct values and out of a visual's control to alter. [It's alluded to in the doc](http://localhost:3000/docs/next/dataset#grain--row-context:~:text=Internally%2C%20the%20visual%20handles%20its%20dataset%20in%20much%20the%20same%20way%20as%20a%20core%20table%2C%20i.e.%20the%20number%20of%20rows%20in%20the%20dataset%20is%20equivalent%20to%20the%20combination%20of%20all%20unique%20values%20across%20all%20columns%20and%20measures%20added.), but probably could be better stated. The solution is as you suggest, but it's also one of the neat features of Deneb/R/Python in that you can add columns to affect the grain of the dataset, but they don't necessarily need to be "used" by the generated visual specification.

I'll be reviewing and updating most of the documentation as part of v2, so I'll add this to my list of things to flesh out (or you're welcome to submit a PR against the doc site if you wish to add something suitable in the meantime).

**Comment by gdeckler** [comment]
Yep, had a feeling that is what it was, would be nice if there was an option in Power BI to not deduplicate data. Thanks for confirming!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
