### ISSUE TITLE
Access to Sentiment and Divergent Colours from current Power BI Theme

### ISSUE THREAD

**Issue by Greg-Philps** [deneb-viz/deneb#272]
Back in v1.3 (not sure of the version, but I think...) the ability to access the 8 individual colours in the current Power BI theme was added (so useful ... thanks!).

Would it be possible in a future version to add access to the additional 6 colours in the current Power BI theme (i.e., 3 sentiment colours, 3 divergent colours)?

Thanks,
Greg

**Comment by dm-p** [comment]
I've checked in a change to 2.0 that will extend `pbiColor` to allow named colors (according to how Power BI names them from the theme internally). There's three groups from this set: divergent, sentiment, and some alternative names (which are basically sentiment). Because it's fun to document Deneb with Deneb, here's their expected usage and how they'll look:

![image](https://user-images.githubusercontent.com/10572054/212586778-3c03252a-f6b9-4353-b472-df7eeabd9293.png)

A couple of remarks on the above:

* The neutral sentiment is different to the divergent middle color in my theme for testing purposes. I actually found a bug in here while implementing and it turned out that the divergent palette was using the sentiment color instead, so this will be fixed in 2.0 with this change also.

* It's not in the screenshot, but you can also pass the `shadePercent` property for these, just like for the indexed colors - I'll ensure this is in the doc when I get to that work.

**Comment by dm-p** [comment]
Because version 2 is still some ways off, I'll be adding this to a version 1.5 build, to provide creators some additional bug fixes and minor enhancements in the meantime. 

The work for this issue is now available in the latest 1.5 alpha build ([refer here if you wish to know how to access and install alpha builds](https://deneb-viz.github.io/community/early-access)) and I will intend to submit to MS for publication and certification by the end of this week (10 Mar 2023) providing that no issues are found during testing. If you wish to validate this change, please do so and provide any further feedback before this date.

**Comment by dm-p** [comment]
You can view the changelog for 1.5 [in the staging area of the Deneb website here](https://deneb-viz.github.io/next/changelog).
