### ISSUE TITLE
Tooltip with signal of item causes call stack size exceeded error. 

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#273]
Apologies for the long spec but I'm fairly sure most of it is irrelevant and just the line below is causing the problem. If you hover over a node with the following in the spec, you get the error. 
 "tooltip": {"signal": "item"},

![image](https://user-images.githubusercontent.com/86846675/211166566-dde30339-7525-409d-be4f-9a0af1ecbe27.png)

On the vega editor, this doesn't happen and is useful for debugging. e.g.

![image](https://user-images.githubusercontent.com/86846675/211166607-53255ece-ef3e-4722-958a-1cbc8bbfcce1.png)

.pbix attached (change extension from .zip to .pbix)

[Deneb Bubble Text.zip](https://github.com/deneb-viz/deneb/files/10367030/Deneb.Bubble.Text.zip)

**Comment by dm-p** [comment]
Thanks for raising - there are too issues here:

1. Logs are too tightly bound to the view. This is the same as #268 and #233 and is already checked-in to v2. For now, you can set logging to 'None' in the debug pane to mitigate.

2. Once you have mitigated point 1, the tooltip object is too complex to display in the Power BI tooltip handler and is silently failing. 

    - This is due to the JSON containing circular references and deep objects that need cleaning-up for JSON. The data and signals do this, but the Power BI tooltip handler does not.

    - vega-tooltip handles this scenario correctly, so you can turn off the Tooltip Handler in Deneb and this will fallback to vega-tooltip, e.g.:"
    
      ![image](https://user-images.githubusercontent.com/10572054/211173131-d5ea7275-994a-4501-8522-acb3f80c1aa7.png)

    - I'll add this to the v2 backlog to address for the Power BI tooltip handler.

**Comment by PBI-David** [comment]
Thanks Daniel.

**Comment by dm-p** [comment]
A fix has been checked in to 2.0 so that Power BI tooltips will work for deep, complex objects, but I learned an interesting thing about Power BI tooltips... they will always shrink content to fit, e.g.:

![image](https://user-images.githubusercontent.com/10572054/212184687-13a777b0-148a-4f4a-8db2-56dca763e196.png)

You can work around this by setting the tooltip text size to be larger, but it is still sub-optimal, e.g. (font size = 18pt):

![image](https://user-images.githubusercontent.com/10572054/212184958-f2511111-f94d-4501-8fe6-532496700557.png)

This is unlikely to improve unless MS changes the tooltip display functionality, and it's unlikely they will, as this isn't a use case for most visuals.

So... we've solved a bug with Deneb, but you still may wish to revert to vega-tooltip for debugging these kinds of objects 😅

**Comment by dm-p** [comment]
While I've been on leave, I've thought a lot about how Deneb's roadmap needs to progress over the short term and v2 has become too much of a monolith. As such, I'll be porting a lot of the work that doesn't potentially cause breaking changes to templates into 1.x and there will be a series of upcoming releases to get this sorted out. V2 will be a longer-term change and I'll be looking to write about this and publish a clearer roadmap soon.

The work for this issue will be included in 1.6, which is already underway. As I could resolve it previously, it'll be available for testing and verification when the 1.6 alpha builds start off (hopefully early July).

**Comment by dm-p** [comment]
This is now available to test in the 1.6 alpha build. [Please refer to this blog post](https://coacervo.co/deneb_alpha_1_6) for an overview of the release contents, as well as links to the change log on the documentation site and how you can assist with testing and validating 1.6 if you are able.

It will be incredibly useful if you can confirm that this issue is resolved from your end, or if anything is outstanding to ensure it is completed. If I don't receive any further feedback, I'll close this off when 1.6 gets submitted to AppSource. Thanks once again for raising the issue and for using Deneb :)
