### ISSUE TITLE
Performance and Dataset Loading

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#274]
When I load the Deneb visual in the .pbix here: https://github.com/PBI-David/Deneb-Showcase/tree/main/S%26P%20Beeswarm%20Chart I notice nearly 800k rows being loaded despite the underlying dataset only containing 126k rows. Does Deneb reload the same dataset multiple times or am I doing something wrong in the way I have written my spec?

Once loaded, the visual performs fine but the loading does take a while and make PBI unresponsive. 

![image](https://user-images.githubusercontent.com/86846675/211353052-73141a8a-d248-42c1-b8d7-9f4cd884be5a.png)

**Comment by dm-p** [comment]
Thanks as always for raising.

First thing (and probably most importantly from an end product perspective), is that the internal dataset processed by Deneb appears to be correct for your dataset (126,499 rows). I've done a lot of validation of the fetched data with a client to confirm the number of rows and values are correct, so I'm pretty confident that this is right. Interestingly, the counter looked correct for them, and has done for me on any other projects I've used Deneb for where we break the row limit.

I've downloaded your workbook and your example is definitely doing the same for me, which is pretty weird. I've checked back on a few other projects I know to be using it and these still seem right, so I'll need to have a more detailed look into why this case is particularly special.

In terms of this number, Deneb should supply the count of rows directly from the interim Power BI data view, so this should correspond with the additional fetching that takes place - the additional fetch is simply Deneb asking Power BI to send more data, until it can't. At each step, you typically see the data view increase by 9,999 rows (as Power BI usually includes the previous row in its TOP N query that's generated and reconciles it when it gets the results back before we get to process it).

Interestingly, if I try this with v2 (to see if it's any better) the visual is failing to fetch more data from Power BI (despite reporting that it should). My tests with other data sets have been working well, so you've helped me find a bug that needs squashing here (not sure if it's related to the case above being 'different' to the others I've seen) - cheers for that! 👍 Once I sort it out, I will try to look into this and see if any fixes can be made to the process for row counts in v2 (although I hope they'll be okay).

Regarding the 'locking' of the main window: this is difficult to mitigate due to the fact that Power BI (and DAX) really isn't built for large visual datasets and may be a design consideration for developers who wish to take this up. It is certainly why MS impose low row limits on their own visuals.

From Deneb's perspective, there are two things going on here while this process is taking place:

1. Power BI is running computationally expensive DAX (TOPN-based queries for each window; to get the next window for each fetch).
2. Deneb is waiting for the main window, and then recursively calling the next fetch (it does not process the dataset until Power BI reports that no more is available, to minimise overhead where we can).

Because JavaScript is single-threaded, the whole window is occupied while this happens. We don't have many options in custom visuals to mitigate this behaviour, due to their sandboxing.

In v2, I am trying to introduce "multi-threading" where it's sensible (or possible) to do so. One area where I can do this is for the data viewer in the debug pane by developing a dedicated web worker for processing this data for display (as it's really expensive). This creates a dedicated process for the computations and allows the UI to be used while this is going on. This does have some net positive effects on other areas of the UI (such as opening and closing the editor while computations are taking place). Your spec has also identified further opportunities for me to improve its performance - so, again - I really appreciate seeing this example 👍

For processing the dataset from Power BI itself, this is more complicated and probably not possible to do in a similar way to the debug pane. For this to work, I need access to MS APIs, as well as shared code in Deneb for processing data and interactivity bindings. This cannot be shared to web workers due to security restrictions, and module workers (which are the official way to implement this) are directly prohibited by the visual sandbox.

Unfortunately, it may be a case of having to live with this limitation if you want to use large datasets, but again, I will try to look at this in more detail if and when the opportunity arises.

**Comment by PBI-David** [comment]
Thanks as always Daniel. 

FYI, in case you weren't aware, I refer to "dataset" as a "source" at least 4 times in my spec and filter each time to get the data I want. I do this as I can't have multiple data sources in Deneb so I combined them all before using in the spec. Hopefully, each time I create a new dataset using source, it doesn't request a reload of the whole dataset from PBI.
```


		{
			"name": "S&P All",
			"source": "dataset",
			"transform": [
				{"type": "filter", "expr": "datum.Channel == 'B'"}
			]

		},
		{
			"name": "S&P",
			"source": "dataset",
			"transform": [
			  {"type": "filter", "expr": "datum.Channel == 'C'"},
				{ "type": "formula", "as": "New Key", "expr": "datum.Company+counter" },
				{
					"type": "lookup",
					"from": "S&P All",
					"key": "Key",
					"fields": ["New Key"],
					"values": ["Percent", "Date", "Share Price"],
					"as": ["Percent", "Date", "Share Price"],
					"default": 0
				}
			]
		}
```

Regarding the 10k limit, would MS not be open to changing their API to allow larger fetches and get rid of the TOPN completely? That would improve things dramatically and would also be useful for other custom visuals too.

**Comment by dm-p** [comment]
Off the top of my head, making changes to the spec will cause Power BI to reload data, as saving the spec is a visual property change and this [causes Power BI to update the visual](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept) (`persistProperties` > _Receives actions from visual_ > _Sends updates to the visual_ > _calls_ `update`), which re-queries the data. 

I've made optimisations in v2 to avoid re-processing the data if it hasn't changed but this can only work if the dataset is < 10K rows (as we don't know if the entire dataset truly hasn't changed without fetching all of it).

Regarding the 10K limit, we're very limited here (at least on Deneb's current Power BI visual APIs). MS have stated there is a conventional 30K row limit for custom visuals, [or you can fetch additional data via this API](https://learn.microsoft.com/en-us/power-bi/developer/visuals/fetch-more-data) in pre-agreed windows of N rows. These data view limits can be either 1,048,576 rows, or 100MB total memory consumed and are not likely to change for performance reasons - both model (as DAX compute is expensive for high-cardinality data) and client (the custom visual and the user's browser memory requirements).

Typically, this number is fixed in the visual metadata and cannot be changed at run time but can be up to 30K, if the author so wishes. Deneb has a 10K window because I've profiled fetches at different values, and this is the best balance of loading overhead vs. query overhead I have experienced. Whilst 30K windows technically get more data per fetch, they take much longer to run and as such it's not possible to update the UI to show that progress is actually going on. Less than 10K, and there's many more fetches (and updates to the visual from the host) and this has the opposite effect in that it's too chatty and causes other UX issues. In some cases, I found that 10K windows would take less total time to fetch all data than 30K windows would (even though fewer total widows are needed).

The latest change MS have made (in API 5.2) is to allow customisation of this number at run time, but the maximum window size for TOPN fetches is still 30K. This also then means that we have to ensure that creators are always up to date with Desktop (as the visual APIs are packaged in).

I'm currently targeting 5.1, as this imposes a minimum requirement of November 2022 Desktop on creators, and this gives an approximate 6-month lag by the time I'm intending to release Deneb v2 (if all goes well). Many users aren't able to install the latest Desktop as easily as some others, so I have to try and balance this out, particularly as Deneb is delivered via AppSource. To move to 5.2 would move the minimum requirement to December 2022. I will think about this though, as allowing the user to change the window size is something I've wanted for a while. It's always been a case of balancing the initial row limit with the fetch, but this could now theoretically open up the possibility of allowing an initial window of 30K rows, with 10K fetches for subsequent windows (allowing the author to override to 30K if they are happy to accept the UX hit).

**Comment by dm-p** [comment]
I've re-tested your visual in the latest v2 build and can confirm the counts are correct while data is being fetched, so I'm optimistic that this particular issue will be resolved when it becomes available.

**Comment by dm-p** [comment]
I've done some testing around the new functionality in API 5.2, and this affects the size of all windows in the data view, including the initial one. This could still be handy in that creators could fine-tune this to the values that make the most sense for their situation. 

Based on previous functionality, we could leave this defaulted at 10K for most users, and then anyone who wishes to break the data limit, can tweak it from anywhere from 100 to 30,000 rows and Deneb will then request Power BI send any subsequent query results for this window size. Or folks can up this to a higher (max 30K) value if their dataset exceeds 10K rows and the fetch won't need to happen.

The only thing I don't like is that this needs a property with a specific menu and name to work, so it can't be added to the existing _Data Limit Options_ menu. Due to how properties are persisted to the workbook and retrieved when visuals are re-initialised, I have a couple of options here if I were to implement:

1. Move all existing options to this new hard-coded menu. This would be a breaking change for existing visuals that break the data limit unless I allocate some time to researching how to 'migrate' properties safely when an existing 1.x instance is replaced with a 2.0 visual.
2. Just keep the existing properties where they are, and just add the window size option to its own menu with a suitably friendly display name.

**Comment by PBI-David** [comment]
Thanks Daniel. I don't mind which option is chosen.

**Comment by PBI-David** [comment]
Hi Daniel - I have created a topojson heatmap [here ](https://github.com/PBI-David/Deneb-Showcase/tree/main/Covid%20Topojson)which seems to be failing when loading large datasets. I have limited it to 9000 rows in PQ and it works perfectly but if you remove that limit and load the full dataset, I don't think all the data is loading and it glitches when trying to do Vega transform lookups (because the data to lookup probably hasn't been loaded). 

Something I don't understand is when I limit the dataset to top 100,000 rows, I see Deneb trying to load far in excess of that. e.g. 
![image](https://user-images.githubusercontent.com/86846675/216769514-7c07571c-5700-4e92-beaa-a82a60b5eff4.png)


Have I misunderstood how dataset loading is working?

**Comment by dm-p** [comment]
I suspect it's a similar issue to what I've detailed above, and I imagine row counts will be correct in v2.0 for this scenario. Probably something we can look into further once 2.0 alpha builds become available...

**Comment by PBI-David** [comment]
The difference this time though is that the full, unfiltered dataset never actually loads. There is not much point in trying to debug the current version and it is probably best just to retest this in v2 and see if it works there.

**Comment by dm-p** [comment]
As this ticket originally talks about the upcoming 2.0, which had a lot of changes folded into 1.6 (which has since been released late last year), this might be out of date or not quite valid for the current state,

We will revisit the dataset processing in what has been re-scoped as 2.0 to make it asynchronous and will track this work under #456. There will also be some UI changes here to reflect the new way of processing the data. I will ensure that we do some checking for this scenario, but I will close this issue to avoid muddying up the backlog.
