### ISSUE TITLE
Errors during Vega template import

### ISSUE THREAD

**Issue by avatorl** [deneb-viz/deneb#278]
I created a basic Vega chart and saved it as a Deneb Template: [JSON File](https://dl.dropboxusercontent.com/s/uxf0fhzrhwmso1p/Diverting%20Bar%20Chart.json)

When I'm trying to import the template from this file I'm getting multiple error messages:
![image](https://user-images.githubusercontent.com/59934292/216765979-56ac2922-b6df-416d-8ca0-1e34a1e32a6c.png).

What is wrong? Vega code has been restored from the template correctly and when copied from the specification window and inserted again using Create New Specification->Vega->[empty] it work with no errors or warnings.

**Comment by dm-p** [comment]
As discussed via DM, this appears to be importing a Vega template but then switching the interpreter to Vega-Lite (as evidenced by the debug pane showing Vega-Lite 5.4.0 as the interpreter). Workaround in this case would be to change to Vega in the settings pane post import but is far from ideal.

This is something that has already been resolved in the 2.0 builds, but will try to do a backport and bugfix release for 1.4.

**Comment by dm-p** [comment]
Because version 2 is still some ways off, I'll be adding this to a version 1.5 build, to provide creators some additional bug fixes and minor enhancements in the meantime. 

The work for this issue is now available in the latest 1.5 alpha build ([refer here if you wish to know how to access and install alpha builds](https://deneb-viz.github.io/community/early-access)) and I will intend to submit to MS for publication and certification by the end of this week (10 Mar 2023) providing that no issues are found during testing. If you wish to validate this change, please do so and provide any further feedback before this date.

**Comment by dm-p** [comment]
You can view the changelog for 1.5 [in the staging area of the Deneb website here](https://deneb-viz.github.io/next/changelog).
