### ISSUE TITLE
Deneb why is diff between Vega and Vega-Lite?

### ISSUE THREAD

**Issue by Klimkiv** [deneb-viz/deneb#281]
good day

I've add Country, City and a measure CityQnty = distinctcount (City) to [Value] area of Deneb visual

1. When I choose Vega-Lite template [simple bar chart] and match 2 fields: Country and CityQnty I've got a perfect chart
2. When I choose Vega template [simple bar chart] and match 2 fields: Country and CityQnty I've got a strange chart where all bars = 1

Why It is so?

Thank you very much!

**Comment by dm-p** [comment]
Hi there, and thanks for your issue. Please note that if you are looking for help with producing a visual, I do not have the capacity to offer free support. A number of resources where the community can potentially assist you are [provided on Deneb's support page.](https://deneb-viz.github.io/support)

If you're reporting a bug, please ensure that you provide more details to help us replicate your problem or provide details such as a screenshot of video that can help us to understand. The information provided is perhaps not detailed enough, as for example, I just did a quick test with a column and measure in a workbook I have open (Location & Mean Temperature) and I get something that I'd expect, e.g.:

![image](https://user-images.githubusercontent.com/10572054/220551406-e32388e2-295d-43b0-a369-65a53e3ab4f8.png)

Looks like the Vega template sorts bars in descending order and the Vega-Lite template doesn't, but the bars are definitely correct for the measure.

This could be due to your dataset in either visual not being the same, as you should get the same results otherwise in terms of how your dataset looks to Deneb.

You can get a better idea of this by comparing both visuals by turning them into a core table visual and seeing how they are laid out. If they differ, you could possibly check to see if you're using implicit measures with a different aggregation, or one of your visuals may be being filtered by another one, resulting in one distinct value. Either way, it is hard to tell without clear, reproducible information from our end.

If you have ruled these issues out and still believe there is an issue, please provide some detailed steps to reproduce, with appropriate screenshots (or short video), and/or a copy of your workbook that reproduces the issue and myself or someone else can perhaps take a look and advise further (or fix if we find anything wrong). Note that if you wish to upload a .pbix here, please give it a .zip extension as GitHub only allows certain types of file extensions.

Many thanks,

Daniel

**Comment by dm-p** [comment]
Thanks for the additional detail - I see the issue now.

The issue is down to the fact that you have more rows in your dataset than the template needs and Veg and Vega-Lite will encode them differently (due to them being different languages).

For example, the bar chart template needs one category field and one measure. You have added two category fields to your visual (Country and City). Power BI will create additional rows for the combination of these values, and if they are not catered for in your specification (e.g. encoded to a different attribute such as color), then the resulting chart may not display as you expect it to. The Vega-Lite chart in your workbook hints at this as well, e.g.:

![image](https://user-images.githubusercontent.com/10572054/220747376-69dd0659-9f32-428e-8460-7c2c6266353e.png)

The artefacts on each bar are the result of each row, rather than a consolidated bar as you might expect - Vega-Lite will stack marks if no encoding is supplied, so it's _sort of_ what you're expecting (but not quite).

For the Vega situation, nothing is handled on your behalf, and you have to be more explicit. This is the nature of the language.

I have duplicated your visual and turned it into a table to illustrate the underlying data, and then repeated the process on the right, but removing the redundant City column. You can see that the chart is as expected, e.g.:

![image](https://user-images.githubusercontent.com/10572054/220745309-6d741398-9062-40fc-8b23-7980e720226d.png)

Hopefully the tables help to illustrate the issue, particularly seeing how Power BI groups and totals implicit measures. This is exactly how the data is supplied to Deneb, so this can be a good way of debugging the 'shape' of your data.

[Read here to further understand row context in Deneb](https://deneb-viz.github.io/dataset#grain--row-context), but in short, don't add more fields than you need for a specific type of chart, or you will get unpredictable results like in this situation.

If you have further questions along these lines, I'd recommend following up on the places linked on [Deneb's support page](https://deneb-viz.github.io/support), particularly [the Power BI Community forums](https://community.powerbi.com/) if your questions are Deneb-specific. On any of these sites there is a larger pool of people who may be able to assist you more quickly than I can (as I develop and maintain Deneb in my free time and am not always able to provide support in a timely manner).

I hope this information is useful for you, and I wish you good luck on your visualisation journey. We've all been there, and it does get better with practice :)
