### ISSUE TITLE
Error when importing a Deneb template from Vega official website

### ISSUE THREAD

**Issue by LuciannaFG** [deneb-viz/deneb#282]
Hello. I went to the the _Vega website_ https://vega.github.io/vega-lite/examples/interactive_line_hover.html and I copied the _Vega-Lite JSON Specification_ in a notepad and then save it as a .json file, but when I try to import it in the Deneb visual in Power BI, I get an error message affirming **this is not a valid Deneb template**. 

I don't understand why, since I am getting the template from the official website. I tried several templates, even the most basic one, and I get the same error message. 
I appreciate all help you can provide. Thank you.

![image](https://user-images.githubusercontent.com/36709188/222394631-7d7398ec-f2ec-4baf-9e4d-05d4c1e1c149.png)

**Comment by dm-p** [comment]
Hi there, and thanks for your issue.

Deneb templates are Vega specifications with additional metadata unique to Deneb that help with field assignment from the Power BI data model [and are documented here](https://deneb-viz.github.io/templates). A regular Vega or Vega-Lite specification does not contain this metatldata, which is why you are getting the message that it is not valid.

If you want to take an example from the Vega or Vega-Litebsite, you can create a new specification in Deneb and then paste this into the editor.

**Comment by LuciannaFG** [comment]
Hi Daniel! @dm-p 

**Thank you so much** for your help. After some fails, I managed to use an example from the Vega-Lite website following the explanation you gave and the documentation! 

I saw that, after creating a new specification the dataset in the code doesn't change automatically even if I specify it in the specification. I have to do the mapping myself, but I believe this is the way that works. 

![image](https://user-images.githubusercontent.com/36709188/222684974-cd4b5cbd-eb68-48e1-a60a-f60ec89f15e1.png)

Have a nice day!
