### ISSUE TITLE
pbiColorDivergent uses "neutral" from Sentiment colors instead of "middle" from Divergent colors

### ISSUE THREAD

**Issue by jsekiewicz** [deneb-viz/deneb#283]
Hi, this issue refers to the 1.4.0.0 version of Deneb.
Using pbiColorDivergent as a scheme for a scale, a gradient is produced from min divergent color, **neutral sentiment** color, and max divergent colors from the current Power BI theme. It should be a middle divergent color, according to the documentation.

**Comment by dm-p** [comment]
This is fixed in #272 and will be included in v2

**Comment by dm-p** [comment]
Because version 2 is still some ways off, I'll be adding this to a version 1.5 build, to provide creators some additional bug fixes and minor enhancements in the meantime. 

The work for this issue is now available in the latest 1.5 alpha build ([refer here if you wish to know how to access and install alpha builds](https://deneb-viz.github.io/community/early-access)) and I will intend to submit to MS for publication and certification by the end of this week (10 Mar 2023) providing that no issues are found during testing. If you wish to validate this change, please do so and provide any further feedback before this date.

**Comment by dm-p** [comment]
You can view the changelog for 1.5 [in the staging area of the Deneb website here](https://deneb-viz.github.io/next/changelog).
