### ISSUE TITLE
Recalculate the visual on exiting from the Edit mode

### ISSUE THREAD

**Issue by avatorl** [deneb-viz/deneb#286]
It will be good to recalculate the visual on exiting from the Edit mode even when "Recalculate during resize" is disabled. Now, if "Recalculate during resize" is disabled, all Deneb chart on the page look broken (wrongly sized) after exiting Edit mode. Such behavior forces to reload the entire page by switching to another page and back each time after exiting Edit mode or to enable "Recalculate during resize".

**Comment by dm-p** [comment]
This currently only applies to Vega visuals and has already been addressed in the current v2 codebase. I'll keep this issue open to track its status though.

Current additional workarounds for this include interacting with another visual on the page, or making a small resize to the container, letting the update occur and then resize back (basically, anything that causes the visual to update or redraw).

The changes to the v2 rendering workflow will also remove the need for the 'Recalculate during resize' property, and this will no longer be present in the properties pane.

**Comment by dm-p** [comment]
While I've been on leave, I've thought a lot about how Deneb's roadmap needs to progress over the short term and v2 has become too much of a monolith. As such, I'll be porting a lot of the work that doesn't potentially cause breaking changes to templates into 1.x and there will be a series of upcoming releases to get this sorted out. V2 will be a longer-term change and I'll be looking to write about this and publish a clearer roadmap soon.

The work for this issue will be included in 1.6, which is already underway. I'll be hoping to have this ready for when the alpha builds start, but I'll keep you posted of its progress.

**Comment by dm-p** [comment]
This is now available to test in the 1.6 alpha build. [Please refer to this blog post](https://coacervo.co/deneb_alpha_1_6) for an overview of the release contents, as well as links to the change log on the documentation site and how you can assist with testing and validating 1.6 if you are able.

It will be incredibly useful if you can confirm that this issue is resolved from your end, or if anything is outstanding to ensure it is completed. If I don't receive any further feedback, I'll close this off when 1.6 gets submitted to AppSource. Thanks once again for raising the issue and for using Deneb :)
