### ISSUE TITLE
"This visual currently doesn't have a specification" while waiting for data to load

### ISSUE THREAD

**Issue by Mike-Honey** [deneb-viz/deneb#288]
My visual works OK once the data has loaded (20,000 rows), but for those few seconds while the data is loading, the visual displays a message including "The visual currently doesn't have a specification".

It's a bit disconcerting for me - I hold my breath hoping it will work each time (it does). I imagine the end-users will be more concerned.

Is there any way to avoid this?

**Comment by dm-p** [comment]
Transferring to correct repo

**Comment by dm-p** [comment]
Hi Mike, and thanks for raising.

This is an issue with the rendering workflow when the visual is initialised for the first time and will not happen after that while the visual is open (the 'fetching' message is displayed for any further updates). It is a known problem but not an easy fix in the v1 architecture.

As such, this has been fixed in the v2 codebase already and here's a quick video to confirm:

https://user-images.githubusercontent.com/10572054/224572979-d20f4449-e7b9-4d9c-a4d7-6c4ce1ed2777.mp4


I don't yet have an ETA for when v2 will be ready, but please be assured that I have already taken it into consideration. We'll keep this issue open to track against v2, as I have a private board with hundreds of tasks that I haven't surfaced publicly, in order to reduce noise.

Regards,

Daniel

**Comment by dm-p** [comment]
This is now available to test in the 1.6 alpha build. [Please refer to this blog post](https://coacervo.co/deneb_alpha_1_6) for an overview of the release contents, as well as links to the change log on the documentation site and how you can assist with testing and validating 1.6 if you are able.

It will be incredibly useful if you can confirm that this issue is resolved from your end, or if anything is outstanding to ensure it is completed. If I don't receive any further feedback, I'll close this off when 1.6 gets submitted to AppSource. Thanks once again for raising the issue and for using Deneb :)
