### ISSUE TITLE
_.%color is not a function

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#293]
Sorry Daniel but found another one. 

I'm converting another spec for use in Deneb. In the attached .pbix, there are two pages. "Broken" is identical to "Working" apart from how a signal is initiated from a supplied measure which is then used elsewhere in the spec. 

Broken:
```
{
      "name": "percent",
      "update": "data('dataset')[0]['myMeasure']"
    }
```

Working:

```
{
      "name": "percent",
      "update": "0",
      "on": [
        {
          "events": {
            "type": "timer",
            "throttle": 0
          },
          "update": "data('dataset')[0]['myMeasure']"
        }
      ]
    }
```
[Gauge Deneb.pbix.zip](https://github.com/deneb-viz/deneb/files/11105878/Gauge.Deneb.pbix.zip)

**Comment by dm-p** [comment]
Thanks for providing another case. I had a very quick look at this and it definitely points to the same root cause as #289 - if I temporarily change Deneb's code to manually patch in the dataset as part of the spec (not intended use) rather than use react-vega's [`data` property](https://github.com/vega/react-vega/tree/master/packages/react-vega#data) (intended use) then it seems to work as we would like. However, this is not a 100% reliable solution due to how the dataset may be set up within the spec by the creator - for instance, I had to manually remove the part of your spec that declared it to get it to work, as it caused duplicate dataset IDs.

I will need to set aside some time to think about how this should work in an ideal state. There are a couple of potential issues in the react-vega repo that suggest this has been an issue for a while, so I may either need to see if I can contribute some work here and fix it properly, or see if I can make a reliable data patching solution work within Deneb. I'll make this a priority when I'm next back onto development and see what I can come up with. Whatever we can come up with will need **extensive** testing though.

**Comment by dm-p** [comment]
Through investigation, I believe that this is definitely a duplicate of #289. Closing this one to reduce noise and to keep discussions in a single place.
