### ISSUE TITLE
Colours assigned out of scale range order. 

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#294]
The phase colours in the attached .pbix are assigned out of order when data is provided by PowerBI (page 2). The same scale definition when used with inline data produces the expected result of colours assigned in order (page 1). 
[Gantt - Deneb Fix.pbix.zip](https://github.com/deneb-viz/deneb/files/11111344/Gantt.-.Deneb.Fix.pbix.zip)

**Comment by PBI-David** [comment]
Assigning an explicit sort fixes the issue but this doesn't explain why it is still out of order and not required in an inline spec?

```
 {
      "name": "cFill",
      "type": "ordinal",
      "range": [
        "hsl(207, 54%, 77%)",
        "hsl(118, 41%, 79%)",
        "hsl(292, 35%, 77%)",
        "hsl(30, 100%, 80%)",
        "hsl(359, 80%, 80%)"
      ],
      "domain": {
        "data": "input",
        "field": "phase",  "sort": {"op": "min", "field": "start", "order": "ascending"}
      }
    }
```

**Comment by dm-p** [comment]
Hi Davide, Regarding the need for an explicit sort: Your inline data is already sorted by ID, e.g.:

![image](https://user-images.githubusercontent.com/10572054/229034991-7f854a28-0f16-4a92-87b1-012c1c666526.png)

In the Power BI version, the data is supplied however Power BI chooses to send it through to the visual (noting that it is not ordered by ID):

![image](https://user-images.githubusercontent.com/10572054/229035105-af52ff0f-b7c0-4b8e-90f4-6efa73df524a.png)

The way to make them consistent is to either apply an explicit sort to the dataset, like you are doing, or you can make ID the first column in the dataset to make Power BI sort it as you intend, e.g.:

![image](https://user-images.githubusercontent.com/10572054/229035400-e13e986e-20e8-4917-814d-99c9f2a36f94.png)

Due to how other users may not know to do this with their data, I would suggest adding the sort if you want this is be a templatable solution.

**Comment by PBI-David** [comment]
Damn it - I must have some brain fog after looking at the code for so long. I should have known it would be obvious. Thanks Daniel.
