### ISSUE TITLE
Colors inconsistency in stacked visuals with and without filters applied

### ISSUE THREAD

**Issue by vbakh** [deneb-viz/deneb#296]
I have a stacked bar chart that takes colors from the pbiColorNominal. What would be the best way to ensure that the same category gets the same color with and without (external) filters applied, similar to what standard Power BI stacked bar chart does?

Here is what I am getting without filters - colors in the native stacked bar chart and Deneb visuals are consistent:
![image](https://user-images.githubusercontent.com/24619419/230941249-c3afd8f8-160d-4959-b92c-473fd87c9ccf.png)

And now with filters applied (BR and CA removed). Native visual keeps the same colors, while Deneb reassigns colors in the order defined in the spec (or default one):
![image](https://user-images.githubusercontent.com/24619419/230941456-4a5d9a0d-863a-41b4-971c-305c6473c2fb.png)

You can find the pbix there: https://www.dropbox.com/s/2e5wciyb2ddhazv/FP.pbix?dl=0

The difficulty is that Deneb sees only data passed into it via the list of Values and doesn't get the rows with the categories that were filtered out (I am curious how native Power BI visuals deal with that). 

The best I can come up with is to read the theme JSON file as a data file with Power Query, parse it (extract colors), build dimensions with <Category, Color> pairs, join it with original dataset and use those explicit colors within Vega-Light spec. 
But I am not sure how to make it consistent with color assignments for other non-Deneb visuals on the page.  

Any other ideas?

**Comment by dm-p** [comment]
With conventional visuals that have data-bound properties (core or custom), the typical logic you would employ is to use the [`getColor` method of the visual host to 'reserve' a specific colour by the data value.](https://learn.microsoft.com/en-us/power-bi/developer/visuals/add-colors-power-bi-visual#assigning-color-to-data-points) Any subsequent values get assigned the next available colour. Note that this will only work for the lifecycle of the visual, so will change if you navigate away from the current tab and back in, which will re-initalise it completely. 

For categorical values (columns), these properties are bound by selector (which is a row pointer, and how interactivity works) rather than explicit values, so you can change a colour in the properties pane from the default assigned and this will stick, but only if the same categorical value occupies exactly the same pointer when the visual re-initialises (measures being an exception as their selectors are explicitly tied to the measure's query name and are therefore mor predictable).

Because Deneb doesn't have the same behaviour in that we cannot create dynamic properties in the pane and everything is declared as part of the specification, you have a couple of options as-is:

1. Declare the `domain` of all possible categorical values in the `color` scale, and then set up a corresponding `range` with the desired color value that corresponds with the index of that domain value. [e.g. for range definition](https://vega.github.io/vega-lite/docs/scale.html#2-setting-the-range-property-to-an-array-of-valid-css-color-strings).
2. Define the colour for a category as a column or measure and pass this into the dataset. [You can then bind the range to that field in the `color` encoding channel](https://vega.github.io/vega-lite/docs/scale.html#example-setting-color-range-based-on-a-field). This would be as functionally similar to the property binding approach detailed above, with the advantage that you could always guarantee colours are consistent for a specific value. However, I don't think that there's anything in DAX to extract the theme colours to automate this if you were looking to tie this together more simply than manually getting the values out of a theme's palette to populate them.

I currently don't have any further ideas as to how we could mimic the behaviour otherwise in the current state, but others might. 

Going forward, it might be possible provide some kind of wrapper for `getColor` as a custom expression that can be used to reserve based on the specified `datum.value` that gets passed.

**Comment by vbakh** [comment]
Daniel, thanks a lot for clarification. Option 2 looks better to me at risk of not matching colors used in non-Deneb visuals (as you mentioned as well).  Per my observations, Power BI sorts categories in the alphabetical order and then assigns colors from the theme to them. It's not guaranteed nor supported, but at least it works for now. Maintenance would be a bit messy too, but it's better than nothing :-)
Thanks again, appreciate your response!
