### ISSUE TITLE
Adding different patterns in multi-series

### ISSUE THREAD

**Issue by LuciannaFG** [deneb-viz/deneb#306]
Hi! 

I am trying to customize the bar chart code to add patterns to each category in a dataset. For the sake of simplicity, I'll use the example on the Deneb page "**Pattern Fills**" https://deneb-viz.github.io/pattern-fills#default-patterns.

**Could you please help me** with the syntax to code a different stripe type for each of the countries in the image below instead of having the diagonal for all countries? 

![image](https://user-images.githubusercontent.com/36709188/235947411-9223afaf-9a40-4c55-9cce-bef71bf64e72.png)

In addition, what if we had the countries as a legend and years in the y-axis? Is there a way we could define different patterns for each country? (please see image below):

![image](https://user-images.githubusercontent.com/36709188/235951139-c798fe8d-5afc-4fa8-b825-cd04a8107296.png)

Below is the part of the code I'm trying to modify to include the patterns in case 2 (I have years on the x-axis and countries in the legend):

  "mark": {
    "type": "bar",
    "fill": {
      "expr":  " datum['countries']='Canada'? 'url(#diagonal-stripe-1-50)' && datum['countries']='France'? 'url(#vertical-stripe-1-50)' "
    },
    "stroke": "black"
  },

I appreciate any guidance you could give me.

Thank you!!

Kind regards,
Lucianna

**Comment by dm-p** [comment]
Due to how patterns have to be generated in SVG, we don't have all colours stored, just the standard ones documented on the documentation page if you want to use thr `url()` syntax. For colour assignment, you'll need to use the `pbiPatternSvg` function ([also documented on that page](https://deneb-viz.github.io/pattern-fills#the-pbipatternsvg-expression-function)). This will generate and reserve SVG patterns in the visual as specified.

For your stacked bar chart scenario, [using the `color` encoding channel will automatically create a stacked bar chart](https://vega.github.io/vega-lite/docs/stack.html#bar), so we can leverage this for your needs. What you will need to do is [create a custom `range` in the `color` scale](https://vega.github.io/vega-lite/docs/scale.html#2-setting-the-range-property-to-an-array-of-valid-css-color-strings) with the desired patterns. Because ranges support ExprRefs, we can do this with a similar pattern, so your example might look like this:

![image](https://user-images.githubusercontent.com/10572054/236050583-31f0522a-04d7-4a93-a847-eaea8ff4a9f0.png)

```json
{
  "data": {"name": "dataset"},
  "mark": {"type": "bar", "stroke": "black"},
  "encoding": {
    "y": {"field": "Year"},
    "x": {
      "field": "$ Sales",
      "type": "quantitative"
    },
    "color": {
      "field": "Country",
      "scale": {
        "range": [
          {
            "expr": "pbiPatternSVG('vertical-stripe-1', 'red')"
          },
          {
            "expr": "pbiPatternSVG('dots-3', 'blue')"
          },
          {
            "expr": "pbiPatternSVG('diagonal-stripe-1', 'green')"
          }
        ]
      },
      "legend": {
        "symbolSize": 200,
        "symbolType": "square",
        "symbolStrokeWidth": 0.5
      }
    }
  }
}
```

I've also made some changes to the `legend` config to make the patterns a bit easier to see, due to how some of them repeat.

For your initial scenario, I would also use a similar method to reduce the amount of expression logic you'll need to manage, but disable the legend, e.g.:

![image](https://user-images.githubusercontent.com/10572054/236058482-c1ca842a-852d-496a-a277-ba4fce33ea87.png)

```json
{
  "data": {"name": "dataset"},
  "mark": {"type": "bar"},
  "encoding": {
    "y": {"field": "Country"},
    "x": {
      "field": "$ Sales",
      "type": "quantitative"
    },
    "color": {
      "field": "Country",
      "scale": {
        "range": [
          {
            "expr": "pbiPatternSVG('diagonal-stripe-1', 'blue')"
          },
          {
            "expr": "pbiPatternSVG('diagonal-stripe-1', 'orange')"
          },
          {
            "expr": "pbiPatternSVG('diagonal-stripe-1', 'green')"
          },
          {
            "expr": "pbiPatternSVG('diagonal-stripe-1', 'red')"
          },
          {
            "expr": "pbiPatternSVG('diagonal-stripe-1', 'pink')"
          }
        ]
      },
      "legend": null
    }
  }
}
```

Note that your scale ranges will need to include suitable assignments for as many categories as you expect, or they will wrap around to the beginning.

**Comment by LuciannaFG** [comment]
That's great and very useful!! Appreciate your help! 

Thanks!

Kind regards
