### ISSUE TITLE
Deneb not loading / rendering

### ISSUE THREAD

**Issue by darrannorman** [deneb-viz/deneb#312]
Hello,

Firstly thank you for the work on deneb - it's a fantastic visual and has served me well.

Recently encountered an issue, where a previously working deneb visual stopped displaying on the service and pbi desktop.  Editing the visual from pbi desktop results in a blank screen, as if the deneb interface has failed to load

Power BI and debeb both latest version

This is the result of clicking edit on the visual:

![deneb issue](https://github.com/deneb-viz/deneb/assets/91427770/27239fff-eed2-4032-98c7-eadb76fa0b88)

**Comment by dm-p** [comment]
The issue with changing from Vega-Lite to Vega is something I'm aware of and will be fixed in 1.6. This one should be resolvable by reinitializing the visual (which will require navigating away from and back to the page with the affected visual).

@darrannorman: if your issue is not related to the above, it suggests there's something in the persisted state that is now crashing the editor UI when it wasn't previously. If you're able to share the workbook with me, I can publish to my tenant and debug. I'll also be able to check the exact spec details etc., just in case there is a specific edge case we haven't caught. This is the best possible outcome for finding and fixing the issue.

If you cannot share the workbook, I may not be able to assist without some kind of detail. If so, doing the following and providing the results may bear some fruit:

* Open the report for editing in the Power BI service, but **do not open the Advanced Editor for the Deneb visual that's affected**.
* (if the visual has already crashed, select another tab in the workbook and then navigate back to the tab with the affected visual to reinitialize it).
* Open your browser's development tools. Instructions for how to do this may vary depending on your browser, but typically the F12 key will open them.
* Ensure that the console is clear, and you have enabled all types of logging (typically *verbose*, *warnings*, *info* and *errors*)
* Open the Advanced Editor in your Deneb visual.
* If the UI is blank, I would expect that you will see an error message in the console - please provide any output from here and add to this issue as a comment.

Please note that I'm still on leave for the next couple of weeks, so may not be able to get to this immediately, but anything you can provide will help me hit the ground running as soon as I'm able to take a look.

**Comment by darrannorman** [comment]
Hello Daniel,

Thank you for your quick reply, all the more as you are on holiday.

Attached is the pbix file to support your analysis.  It is regarding my company work - nothing top secret but do keep the file to yourself.

Best regards and enjoy your break

Darran

**Comment by dm-p** [comment]
Hi @darrannorman - I think because you replied by email and .pbix is not a valid extension type for GitHub issues, the file probably did not attach (I didn't get it in my inbox either). Could you possibly email to daniel@coacervo.co when you get a chance please? I'm still on leave but figured I'd ask ahead of me getting back home so I can look at is ASAP when I'm back.

**Comment by dm-p** [comment]
This has gone stale, so closing. If further work is required, please re-open with the requested details and I can take a look.
