### ISSUE TITLE
Renderer Issues

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#313]
Hi Daniel - apologies but I think I have identified a handful of issues all related to a tree chart I have published. Some of these may be Vega issues but I'm not 100% sure so I'll list everything and see what you think. Examples are all from attached .pbix. I know you're away so don't feel the need to respond until you have more time. 

1. Render quality between editor and final visual is very different. 

In the editor, the quality of the render is crystal clear. e.g. 

![image](https://github.com/deneb-viz/deneb/assets/86846675/acfbcc1d-be8f-46f8-a3b9-3f55765f937b)

However, if I close the editor, the quality of the render is very blurred and this becomes more pronounced with zooming in and out with the mouse wheel. 

![image](https://github.com/deneb-viz/deneb/assets/86846675/5471719d-3abe-4f36-a089-ab69434ac178)

It isn't easy to tell from screenshots so hopefully you can see with your own eyes when you test. 

2. If I switch the renderer from Canvas to SVG, the blur goes away but another problem is introduced. Observe the KPI bars at the bottom of each node.

![image](https://github.com/deneb-viz/deneb/assets/86846675/0354e6d7-48df-4055-a3c7-3095daeb1c56)

When you zoom in, these KPI bars disappear but only in the SVG renderer. Weirdly, zooming out isn't affected. 
![image](https://github.com/deneb-viz/deneb/assets/86846675/d1157f0c-feff-4ec3-8cf5-147d6da58679)

3. Is there a way to specify the sort order of the dataset? For some reason, the dataset is supplied by Deneb in reverse compared to the standard online Vega editor and the tree transform doesn't currently support sorting very well. 

[Test.pbix.txt](https://github.com/deneb-viz/deneb/files/11524712/Test.pbix.txt)

**Comment by PBI-David** [comment]
Did you ever work this one out? I can't test on the new alpha build as it is loading remote resources. 

![image](https://github.com/deneb-viz/deneb/assets/86846675/f733c639-9234-4105-b4af-faac7ff548b4)

**Comment by dm-p** [comment]
I've attached a version of the alpha with the remote loading enabled, that you can use to try things out. Just remove the .zip extension and it should load in just fine:

[STANDALONEdeneb7E15AEF80B9E4D4F8E12924291ECE89A.1.6.0.20230911#812494b.pbiviz.zip](https://github.com/deneb-viz/deneb/files/12580727/STANDALONEdeneb7E15AEF80B9E4D4F8E12924291ECE89A.1.6.0.20230911.812494b.pbiviz.zip)

I have to apologise in that I haven't really looked in-depth on this one, so I'll provide some answers to the best of my knowledge.

1. Yes, the canvas renderer will be blurrier when you return to the report. I assume that you have your report set to fit to page? If so, Power BI will set the zoom to something that won't be 100%. MS doesn't provide us with the canvas zoom level, so we can't manually adjust the canvas renderer to offset it accordingly. As such, it looks fine in the preview, because it's always at 100% zoom. If you set your report page zoom to 100% it should look as crisp as the preview. I have asked MS before for access to the canvas zoom level, but they are not prepared to add it to the custom visual APIs (although I will continue to ask each time I meet with them).

2. I can't speak for this and suspect it might be something to do with Vega's SVG renderer. We could probably inspect the DOM in the Power BI Service to see if the shapes are still present but offset incorrectly. Does this happen in Vega Editor?

3. You should be able to sort the data from Power BI by adding columns and measures in the order that you want them sorting.  MS have recently added a sorting API that we can use if you want to be more explicit. This will require a change to the Deneb template structure, as I would want to ensure that sort order is carried across for anyone loading a template back up. Feel free to raise an issue for this if the current approach doesn't work and I can schedule for 2.0 (or earlier if the change can be done in a non-breaking manner; I will have to do some R&D to determine).

**Comment by PBI-David** [comment]
Thanks. 

1. Yes, you're right. It is PBI setting the zoom and when at 100% the render is clear again. This also happens for other specs but I never noticed before. I will just use the SVG renderer instead of canvas as that is a poor user experience. 
2. This happens in Vega Editor too so I think a Vega bug. 
3. I'll raise a separate ticket for this as the tree transform doesn't work properly and so additional sort columns have no effect.
