### ISSUE TITLE
Edit button missing on Deneb visual in Power BI

### ISSUE THREAD

**Issue by mlongoria** [deneb-viz/deneb#314]
I have a PBIX file with 4 pages. Each page has a Deneb visual with different vega code. Only one of them has lost its Edit option in the menu. I'm not clear on why. I can recreate my visual so it's not urgent - I'd just like to understand why. The next Deneb visual I made didn't have this problem. So maybe it's something in the code that caused the issue? Nothing changed in the data model. And there are no errors, just no Edit option. The Deneb visual is version 1.5.1.0. PBI Desktop is version 2.116.966.0 64-bit (April 2023).

![image](https://github.com/deneb-viz/deneb/assets/20218384/316eb255-b31c-478a-aad3-c02f9d6c84c1)

**Comment by dm-p** [comment]
This is interesting... the Edit button behaviour is governed by the main window (the visual just declares in its metadata that Power BI should enable it, which is read when the visual initialises).

If this is consistently happening when the page is opened, then it suggests some possible corruption of that visual's configuration by Power BI, but as the report configuration isn't documented by MS it might be something I have to pass on, but if you're able to pass on the workbook I can take a look and see if there's anything specific that sticks out.

It might also be worth trying to re-add the visual from AppSource and then navigating away from the current page and back to force re-loading. This can sometimes undo transient issues with custom visuals in reports (although I'm not convinced it will work in this case).

**Comment by mlongoria** [comment]
Yeah, I figured it was really a Power BI Desktop issue. I was just hoping you had encountered it before and could tell me how to fix it. I see we can't upload PBIX files, so here's a link to download it from OneDrive: https://1drv.ms/u/s!AtDPLqci_xrRh_Is9B8_epny-aSpyQ. The visuals with the issue are on page 2 and page 4 (I had another visual on page 4, but I deleted it and replaced it). Page 4 is where I copied and pasted the visual from page 2. Please ignore my weird visuals as I was trying to learn about circle packing and beeswarm plots. :) Re-adding the visual from AppSource did not fix the issue.   No worries if you don't have time to look at this, or if it's really just out of scope for you.

**Comment by dm-p** [comment]
I'm unsure if this is still an issue, but in v2, we will move away from the advanced editor 'mode' toggle in the visual header due to its lack of discoverability, these weird quirks where it sometimes becomes unavailable, and lack of dedicated APIs around its state management from MS (whereas we get some decent support around toggling focus mode state). 

In v2, the editor will be available through the following conditions:

* A report is in 'Edit' mode (i.e., editing in Desktop or opening a report in the Service and selecting _Edit_ from the main menu).
* You put the visual into focus mode (or Deneb does via events or controls on the visual canvas)

As such, I'll close this as "won't fix," and we will concentrate all effort on the above conditions and workflow in v2.

Of course, please continue to advise me of any issues you notice around Deneb as you find them, and I'll do my best to incorporate feedback for future versions. Your feedback is extremely valuable :)
