### ISSUE TITLE
Bad Plotting with "Page Refresh" and Memory leaks leading to Webview2 crashing

### ISSUE THREAD

**Issue by s-aql** [deneb-viz/deneb#328]
This is in reference to PowerBI Community subject 
https://community.fabric.microsoft.com/t5/Desktop/Deneb-Visual-Vegalite-Bad-Plotting-with-quot-Page-Refresh-quot/m-p/3344987#M1115514

If you need access to the environment to test and troubleshoot please let me know

**Comment by dm-p** [comment]
Hi and thanks for raising here. As stated on that post, your setup seems to be very unique to the problem, we don't know the profile of your data and I don't have financial or time resources to set up a DirectQuery implementation. I would also need your spec and data so that I can understand the plotting issue - there are still some things that it might be, but it's hard to tell without being able to see the point-in-time data when things go "wrong". 

Regarding the refresh issue, I would also need detailed steps as to how this is set up and being triggered to run every few seconds - as far as I am aware, visual datasets don't auto-update unless there's some form of external stimulus like a web page refresh in the Service, setting up the Play Axis slicer to cycle through a lot of data points (ensuring no caching of the result set), or using auto page refresh in Desktop (as mentioned above I don't have the ability to test this as it only becomes available for supported data sources).

You can provide access details privately if needs be at daniel@coacervo.co. To manage your expectations: Deneb is a free and open-source project and I only have a limited amount of available time to investigate bugs. This particular issue might be very complicated due to the number of moving parts and I'm not sure at this time just what might be involved in debugging and/or fixing it. I will look into it and see what I can find out, but I can't provide any solid ETA on when it might be fixed.

**Comment by dm-p** [comment]
I made some performance-tuning improvements in 1.6 that should have resolved this issue. I tested this with the OP's dataset and report and confirmed that it had much more stable uptime from my end, but they never replied whether it was resolved for them. I'll assume that no news is good news.

**Comment by s-aql** [comment]
We have tested it, although not for an extended period of time, but the issue seems to be solved.

Thanks Daniel.
________________________________
