### ISSUE TITLE
Secondary axis tick marks missing when choosing "resolve": {"scale": {"x": "shared"}}

### ISSUE THREAD

**Issue by RiyadBkhsh** [deneb-viz/deneb#366]
Hi, I am trying to make secondary axis where times will be shown and after to replace with some names, but this times should be connected so I cannot use "independent" in "resolve". So I am using "shared", but this time there is no tick marks is showing at the top of chart. But when selecting "independent" it is showing. Is there any solution for this behavior?

**Comment by dm-p** [comment]
Hi there, and thanks for raising. This is going ro be hard to diagnose without any supporting information, such as specification or workbook. Can you provide a resource like this that reproduces the issue? Is the behavior correct if your build your visual in [Vega Editor](https://vega.github.io/editor/)? If it is incorrect in Vega Editor, I would suggest you raise a bug in the [Vega-Lite project](https://github.com/vega/vega-lite), as we can't support issues with the languages in this project. If Deneb has incorrect results vs. Vega Editor, I'm happy to take a look for you, but (as mentioned) if you can provide a resource that helps me to replicate the issue, this will help a lot in being able to find the root cause and hopefully fix it.

**Comment by RiyadBkhsh** [comment]
This is code in vega editor, [https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscIA6hmADQAEADAJyUCCaA5pQEzVsDMNAbHNWoDqlAOIBZACohyIAEbwSZKnUYt2nHgEYA7MLjcxUmSADGihlpNhFAISuysMAE5QA+lACWAWwyKAytBUXCIAIhimlFoAHLT01PyCwkbSsqHQfkSkFDT0TKwc3CAAvuQEitkqeeqF2kJJgikmClnKuWoFmlHRAmxwXFpNsuZEDGzWduOOLu5evgFBlCGU4ZExcVEALPqNEqkg6VCZSjmq+RpFpeWtp9Wdhlq0AloCOkPyFW1nNV1sfdQvXTvEYgSwTIi2KYgJwQVweHzHQJQYJhCLdDZ-HYiPYmQ7HSrtc61EoAXVKIAwADtTAB7MCeSnMeCgACezJAADNPBgUDYiOZZFAWQAHY405z0ymoExeKAoTKUtAoFCyCAAD08OAQIBQEDkPIAwjSUOLFHJdaYANYlYrk3UsjDOPCgYWwiDeLX4EBS+ZEAAWnmYfpQgb9UBMWB5EXD2qFosUwppDPDshplMU3hpaEjNMQjptZW97uOzGcnhsjijphjIGTjuQKGaDL50NMqGwJULPrFws8tO8wojVZjoDjx0TyZMXJ5YE94BAZNkcmbinlzCpNmKJNk3lh1tjIuOclhEagzhplqPFut5KptMlTO1avZ095ilggsPiiOA-F0tVGpaqAur6igACiarCk6RCQFAaDeAAdCBPImMhKBGia0HyNeJiluW8Bnpgsh4WA6RYH6eAAKwIZR24gCRGGmkQpYYGysgAF7Nhgz5wFo5KyvKiiSAiAD0oRoM40CeGmnYgGq4zaq+LYKOStKYS+3JvjBEZtoJ2pgDSu4MngID2CYkILrIkmMpkuAgAAxAAYo5Oi0IIJj2ToDC2NE7mLjqGDrpSfKjp4crHGqkURiy3hyMa-hnheGCMVhABySqNo4MVxSgkhfkQWAAI5oLCfiyGhAAyPhhfAWgcLa0znpexDllAFHarSwVhdJ6ZwF6rqSd4igBkGIZBimFIDkK8AcqgkayA2mC1VuC2oEtAjkjSrqmGFbIdWm9JeDJfWjtgI6cppLZuG4kbytWZDXSYGDFdKRA0hyHKyYtmTUDRVwgAN7qKFtfaGYOq3oJkfF0d98C-ZRtr-WeECUlgHLikNJ0gHMGAAKqUjVRAOrCmaUm1sEYH6WbOFg3gMmgRxYJGnWzlOl2KDCcI4yYEBauAGTc-9ummEqGSKBTOMABTE84kuwfBCF4gAlFQpNtXL0AK8rVAUxrcGIdrlBUxJWB6wrnOzAiKuUHTiqM2biEW-CvjW8zB2m-LjszM7GBK0rPN85SGAAO7CfMK0gLuzj7qO+XY321qNUlZo4be1J0gyj6gDxoBKYoQehwiMpxz+iaSZlIDqpq7JoRBUHi5riFoaheqGsaTHYRAVq4WWfKERgxG92R7W4NRtEcVxPF8fxNLGl4g5Y3nRAF2HZXx+FihgXmZOUAlsJQJQq-F-GRCl3+Ffo84u41gApGAAC0N9yI-LKUDfAAScA3+IX-+KStp0WcNgY0eZ2RYF0pkbOiguKimClScMDUzBpi5FnSugF2QCWSu3LC5ou43ltEAA](url) so now x axis is in independent state and secodnary axis displaying but not connected with main axis, when I am switching it to "shared" it is considering only axis at the bottom I guess, at the top ticks dissappearing.

**Comment by dm-p** [comment]
Thanks for providing a link. This appears to be a question about Vega-Lite rather than Deneb itself. If you have any questions about the languages, [please refer to Deneb's support](https://deneb-viz.github.io/support) page for getting public support on the languages. Unfortunately, I do not have the bandwidth to provide this kind of support (although I am available for consultation; link also on the provided page). 

If you are sure that Deneb is behaving differently to Vega Editor, we definitely want to fix those kinds of issues, but please confirm this before raising here as I only have limited free time to provide help to the community, and we need to prioritize legitimate issues as much as possible.

As a gesture of goodwill, I am not sure if this solves your issue, but hopefully shows that you can share an axis and style the labels differently. I have specified `orient` to `top` for one layer's axis and `bottom` for another. I have added different formats to show that they can have different labels whilst remaining shared. Note that the `resolve` parameter is not used, so both axes are shared. I have also modified the `labelExpr` for the top axis to only render dates for new days (hour of label value == 0):

![image](https://github.com/deneb-viz/deneb/assets/10572054/b933ddf2-0c78-4522-9783-8620a2c6b3e7)

[Example spec here](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscIA6hmADQAEADAJyUCCaA5pQEzVsDMNAbHNWoDqlAOIBZACohyIAEbwSZKnUYt2nHgEYA7MLjcxUmSADGihlpNhFAISuysMAE5QA+lACWAWwyKAytBUXCIAIhimlFoAHLT01PyCwkbSsqHQfkSkFDT0TKwc3CAAvuQEitkqeeqF2kJJgikmClnKuWoFmlHRAmxwXFpNsuZEDGzWduOOLu5evgFBlCGU4ZExcVEALPqNEqkg6VCZSjmq+RpFpeWtp9Wdhlq0AloCOkPyFW1nNV1sfdQvXTvEYgSwTIi2KYgJwQVweHzHQJQYJhCLdDZ-HYiPYmQ7HSrtc61EoAXVKIAwADtTAB7MCeSnMeCgACezJAADNPBgUDYiOZZFAWQAHY405z0ymoExeKAoTKUtAoFCyCAAD08OAQIBQEDkPIAwjSUOLFHJdaYANYlYrk3UsjDOPCgYWwiDeLX4EBS+ZEAAWnmYfpQgb9UBMWB5EXD2qFosUwppDPDshplMU3hpaEjNMQjptZW97uOzGcnhsjijphjIGTjuQKGaDL50NMqGwJULPrFws8tO8wojVZjoDjx0TyZMXJ5YE94BAZNkcmbinlzCpNmKJNk3lh1tjIuOclhEagzhplqPFut5KptMlTO1avZ095ilggsPiiOA-F0tVGpaqAur6igACiarCk6RCQFAaDeAAdCBPImMhKBGia0HyNeJiluW8Bnpgsh4WA6RYH6eAAKwIZR24gCRGGmkQpYYGysgAF7Nhgz5wFoqZllSNZyDSUBQDS3hTuKu41gApAAEnAMniIp-idiAsryookgIgA9KEaDONAnhpmparjNqr4tgo5K0phL7cm+MERm2mnamA4kQAyeAgPYJiQgusiGYymS4CAADEABiEU6LQggmGFOgMLY0RxYuOoYOulJ8qOnhyscaoFRGLLeMJKD+GeF4YIxWEAHJKo2jjFaVkhfkQWAAI5oLCfiyGhAAyPi5fAWgcLa0znpexDllAFHarSWW5cZ6ZwF6rqGRJ-qhiGQYphSA5CvAHKoJGsgNpgw1bqdqDnQI5I0q6pi5Wyc1pvSXgmSto7YCOnIOS2bhuJG8rVmQAMmBgnXSkQNIchyalnZk1A0VcIBre6ij3X24mDld6CZFol0gAj8BI5Rtoo2eECUlgHJSc66kIgAqpSQ1EA6sKZpSM2wRgfpZs4WDeAyaBHFgkbzbOU5-YoMJwnMPUgBAWrgBk8udqALmmEqGSKDz8sABTs84+uwfBCF4gAlFQnMzSb0Bm5bVA83bcGIY7lB8wZWAu2bsuzAiVuUELiqiz7iF+-CviB+Lr3e6b4czJHGAWxbJhK4olIYAA7tp8yE7uzj7qOrUM1ap4TVeEBl7e1J0gyj6gDxoCWRn2e5wrY7fhgv6GQ1iuAeyaHVWaOHEWWfKERgY-lmRs24NRtEcVxPF8SA4rclz373ZJzjSYoMlgAAtDJcjH2xOp6jyEFQYonsC2HuAAOQI4-JIW5QAC8H80JQAD8lDxyfmhV+lA4CUEfo-As6kaTGi8IOT6v0ZytxzgiGUuVXIgDAnmLmlByqwigJQduMoS4-kTL3Ukto6LzS5A3fump2QaSqsaJi2Eq43ltEAA).

If you have any further challenges with this, please follow up on one of the public help forums. Good luck with your work and thanks very much for trying Deneb!

**Comment by RiyadBkhsh** [comment]
Thank you Daniel, for the idea. I think it will be enough for now. I will try to make some modification inside code to make final version.

**Comment by RiyadBkhsh** [comment]
One question that, is it possible to change time label with aother data? Like I want actually to display on top axis some time names, like for 06:00 "Morning", 14:00 "Afternoon", 22:00 "Night" etc. I have data for that which shows which name associated with which time.

**Comment by dm-p** [comment]
Axes aren't connected to data at a row level, so you can't easily look this up; temporal and quantitative axes particularly as they are linear and not categorical.

Personally, if you're using a 24-hour clock in your axis, it should be evident to the reader when morning and afternoon is and this may create redundant information and cognitive load. However, if you do want to do this, you could change the `labelExpr` to something like the following (and remove the `format` property as it's no longer relevant):

```
"labelExpr": "[timeFormat(datum.value, '%H:%M'), hours(datum.value) < 6 ?'Night' : hours(datum.value) < 12 ? 'Morning' : hours(datum.value) < 20 ? 'Afternoon' : 'Night']"
```

![image](https://github.com/deneb-viz/deneb/assets/10572054/81f26973-b8b9-4e93-83b4-aa1602091582)

Note that I've used an array, which will put the time of day on a new line.

[Here is the spec](https://vega.github.io/editor/#/url/vega-lite/N4IgFgpglg5mAuIBcBWADAGhAdygE3jGQBZ0s8BDeC5UANwoBsBXCAZ2QG1QakQB1CHgwACNAE4RAQWYwRAJjTyAzGIBsSNGk1oRAcQCyAFRBYARsgFDRE6bIVLVARgDsOpCv3HTIAMaWpJx88SwAhIKw2agAneAB9eCgAWwhLAGUqUWVdABEIXxEnAA5xSTQNLR0vEywcqlS+QWExSRk5RRUQAF8MHksmm1b7DudtSq1qnwtG6xa7dsdCos15JGUnSax-Pil5YLC9yJj4xJT0zJFskTyC4tLC4ncJwxqQOvgGq2bbNodOnr6M2+QwWnic4k0Tk0Lk2IGmX0G8z+qnkqzQUNcsO2IEC+z4oUOICiFFiCWSnwy8CyuXyS3uqKeuhePnenwGc1+I26AF0eiAIAA7XwAezwUAFMFoIAAnlKAGZQCCMEJ8fxYeDSgAOn2F0TFAqYPkS8EYDQFzEYjCwFAAHlAOEhQIwKGYlQBhYWMXWWMzO3wAa26XT5zulEGiXFAmpJFCSDu4IANZz4YFgYEYacQkSV+UQjpAGu1lk1wvFWZAwoFliSwuYbAgwro4aDvUTsc+MGi+B89dNvjzIDL4YYjCm4pVRN8THY3VbSZ1mqgIqSmp7Of7UsLnxLZZ8CqVeHjIBCvPM48sppggpCXW5WCSJMD+a3PpJPfg0WF-s+vooAdn-JCqK4qSvmNryoqyqWDQ6pap8HwrrqhrWnaDpOi6SoAKI2pqEZ8JwpwQAAYrqD7wAAFJQ8DMEkAB0I6sKIADkACkAASSAsQYTEAJSiGAtbRGwlFUDR9FMKwPEiAAPCIagiAA-ExABymZMSISAiAJzBCSJ1F0QxEBSbJTjyIpIhMQYuoCiB6madpulUWJhnGQ45lMVIcofNEArCpWdkWapcDwEx3I+M6rqMB6Xp4XCfqBlgnbdkgH6MSASV4HUbBEEgnAoLRKB3ulXZ4NF3p8J2ECylgABe44QOBSBOFguqKgKA5mMK8DwMKSQAcapqWEY5IAPQ5DpVBQJWAE2ns+b7lBfAWHyIoxRBB6WCEkRToN+Z4L1FDilwIDhD4BIgEV0QUBKDScCAADERFES44haD490uFIoRFG9p4gJe16blAJqfDaYM9tKSSdYwaQfl+EBlbFykWqOkSQ9DRhwZYbAAI7MCSqRYBFSoADLJMDyCmWgwZHJ+378PghBSiKApiok025VGMZ9SmaYZsFPgQCuGrIHKTD1lghmU7eksSQ01MtdGvjA7K+Ys2zU1VpzBbsHmoALROcRxL2uZCEbgt44afDCnKcoAVLmgFQCIDRldPMVouy6rrLLANE4MsgA7aBOzToAftdbByqRkYFuSACqNkDmGJI1u1YBURADlsEk4rMB8bD1urHBYAb2PHGSZzWg6x71IRs6gDtvgWvUm21+S5HJ9EeliayfEiKnhDd3RveiBnQ+0SPWmCcJTl0cSpKEX3Ofmvn4-zyc5J94XlaHmv5eLzxPgUNXAoQNgw1nAHD7RE+YdY3wiT-rT8M+vFAGCiK+qgaAjX65BE6n3PuSI098daISuqjEAtp7RSmJlFT05U4p-gSsVZKqUICJRKllHKeUCpFTqqzBqlMWpdkFAOHq3sQBR2iGRSwLE8AAFoWJmCYdVf6GFGDYVwpYLOQ9OBMUMqFKSABeYRYhzKz34XA0KGkLJMRbAWPyjBEirm1qXPggCL6E1jiDSwmEmztRELDEk8ARBaJAUWB+QsSwQJ5MGIqLMFTfygahIGINEav2QUGLoQA).
