### ISSUE TITLE
Inconsistencies in VEGA Transformations within DENEB: Versions 1.5 and 1.6

### ISSUE THREAD

**Issue by CSalcedoDataBI** [deneb-viz/deneb#378]
I've identified inconsistencies when executing the "stratify Treemap" and "density" transformations from VEGA in DENEB.

In DENEB version 1.5, the data panel doesn't display any information, and the Treemap visualization doesn't render. You can observe this behavior in the following image:
![Treemap Deneb 1_5](https://github.com/deneb-viz/deneb/assets/73630372/86adfdc8-7f99-4d65-80ab-b3598f04268f)

In the BETA 1.6 version, while the data panel displays information, the graph visualization still doesn't appear. You can see this behavior here:

![Treemap Deneb ( BETA )](https://github.com/deneb-viz/deneb/assets/73630372/14daa422-cdd0-431a-9d9a-771a42bacc8f)

Upon reviewing the code, it seems the transformations aren't executing properly. I'm uncertain if this is an error on my part or an issue with DENEB. For clarity, I've shared the official VEGA examples I tried to replicate in DENEB:

https://vega.github.io/vega/examples/u-district-cuisine/
https://vega.github.io/vega/examples/treemap/

Additionally, I've attached a .gif image showcasing the behavior with the Treemap and a link to download the PBIX file

https://github.com/cristobalsalcedo90/cristobalsalcedo.github.io/blob/f146d8f454c7868053c4ad71b6262ae5752a68f7/Treemap%20Deneb%20(%201_5%20%20--%201_6%20BETA%20).gif

https://github.com/cristobalsalcedo90/cristobalsalcedo.github.io/raw/main/Treemap%20Example.pbix

I appreciate any feedback or assistance on this matter. I hope this information proves helpful.

**Comment by dm-p** [comment]
Hi @cristobalsalcedo90, and thanks for raising. The behavior in 1.6 is due to Deneb returning the visual dataset (rather than the Vega view data) in the event that the Vega view does not provide any information. In 1.5, it appears to fall back to the behavior of displaying nothing, due to not having any information from Vega in this case.

I will need to investigate why this case does not work (likely due to differences between Vega Editor's processing or the Vega view, and Deneb's reliance on react-vega to manage the spec processing and rendering). However, as this is currently a production issue, I will not be planning to address prior to submitting 1.6.

**Comment by cristobalsalcedo90** [comment]
Hi Daniel,

I greatly appreciate your prompt and timely response. I want to thank you for your dedication and ongoing efforts in developing Deneb. Also, thank you for delving into the investigation of the issue I raised.

I understand that the difference in behavior between versions 1.5 and 1.6 of Deneb is due to how information is handled in the context of Vega view and react-vega. Your explanation about why this behavior occurs is very insightful and provides me with a clearer understanding of the situation.

I will do everything within my capacity to uncover any additional details that may be relevant to resolving this issue. I hope our collaboration can contribute to a satisfactory solution.

Thank you once again for your assistance and commitment to Deneb.

**Comment by CameronGH** [comment]
I had a very similar problem. After a lot of hair-pulling, it turned out that I just needed to tweak the data for my root node by making its parent null.


From here: https://vega.github.io/vega/docs/transforms/stratify/
_"To indicate the root node of the tree, the parentKey value must be one of null, undefined, or the empty string ''."_


So it might just be a pesky quirk of vega and not a deneb bug that you're experiencing :)

**Comment by dm-p** [comment]
I believe that @CameronGH's answer is correct from a language perspective. If you still think this is an issue for Deneb, please re-open it with details, and we can investigate further.
