### ISSUE TITLE
Right Click - > Show as table

### ISSUE THREAD

**Issue by sm-thirdman** [deneb-viz/deneb#389]
When you right click on a Deneb visual you get the 'Show as a table' option, same as any other visual.
For some reason MS have failed to put in an option to turn off this behaviour, which makes it a major security issue.  Sensitive data used within the visual for calculations or graphics, but should not otherwise be visible to end users, is made visible in this table.

I was wondering if this was something PBI left to visuals to implement, in the same way you describe cross filtering and highlighting?

Ideally I would want to modify the dat in this table (remove columns) or, better yet, just have it blank.

**Comment by dm-p** [comment]
No - this is something that is present in every visual and is part of the container itself (which is MS-owned; only the content inside the container is owned by the developer). We have no control over what options we can display in the context menu or visual header, and the 'show as table' view display and workflow are controlled by Power BI rather than the visual. We also don't know if Power BI is even in this state if/when a user opts to do it, as there are no API methods that allow us to detect its state.

This would likely need to be a feature request to Microsoft for Power BI in general, to be able to control the ability to show or hide this option on the container as a report author.
