### ISSUE TITLE
Vega emitting too many data listener changes causes UI issues

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#391]
Sorry - think I have found an editor crash when looking at datasets. To recreate:

1. Open attached
2. Edit visual
3. Click close to acknowledge version change
![image](https://github.com/deneb-viz/deneb/assets/86846675/03e209fa-31dd-4847-b4d9-2260caaf0329)
4. Click dataset dropdown
![image](https://github.com/deneb-viz/deneb/assets/86846675/e3292787-ee27-43b3-87c7-e74a94e38ad1)
5. Select marks dataset
6. Observe that the table is broken and user is now unable to switch between datasets (the dataset dropdown flickers for a split second and then disappears)

Most of my specs are fine but this is happening on a couple of them. 

[Deneb Bubble Text - Copy.pbix.zip](https://github.com/deneb-viz/deneb/files/13280168/Deneb.Bubble.Text.-.Copy.pbix.zip)

**Comment by dm-p** [comment]
Thanks for raising. I think the issue is that (for some reason) we have this error in the log on 1.6 when you switch to that dataset:

![image](https://github.com/deneb-viz/deneb/assets/10572054/e20bf7c0-cf96-45cb-b169-7cb67b2554a4)

From 1.6, Deneb is designed to fall back to the visual dataset in the event of errors or no valid data streams in the view, as the Vega view typically doesn't have anything to display, and it makes sense to try and show the visual dataset in context rather than nothing (like versions < 1.6 do). But this doesn't appear to work as intended here either (I would typically expect to see just `dataset` in the list if this happens).

I'll have to investigate what's going on in this specific case, as I can briefly see that the data viewer does briefly return the result for the desired `marks` table before the Vega view fires the error event. If the Vega view fires errors post-parsing and initial render, we probably shouldn't fall back to this state as it makes debugging difficult (as we're observing here).

A workaround appears to be to update and apply the spec to clear the error and re-select the `marks` dataset, e.g.:

![image](https://github.com/deneb-viz/deneb/assets/10572054/5781517a-7b1e-4ed6-8b11-63b426ea409f)

**Comment by dm-p** [comment]
Out of interest: the sample workbook uses the AppSource version of Deneb, which is still v1.5.1 for me. Is AppSource v1.6 live for you in your reports?

**Comment by PBI-David** [comment]
Thanks Daniel. Yes, v1.6 is live for me.

**Comment by dm-p** [comment]
Dedicating some time to investigate further. It would seem that we're getting an infinite loop when we extract the `marks` dataset from the Vega view. The view generates the 'stack exceeded' error, possibly due to how the listeners are being cycled for the debug pane. More work is required, but I think I'll up the priority on this one and try to get it into 1.6.2.

**Comment by dm-p** [comment]
Hi @PBI-David - I have a build that I believe fixes this - I've been testing on your workbook, plus some others that I have for testing dynamic updates of datasets (like the stores that Vega-Lite creates) and these all seem to be good.

If you're able to confirm that you're happy with this, I'll work on packaging up and submitting to MS as soon as I can.

[ALPHAdeneb7E15AEF80B9E4D4F8E12924291ECE89A.1.6.1.20231122#a973bf2.pbiviz.zip](https://github.com/deneb-viz/deneb/files/13433834/ALPHAdeneb7E15AEF80B9E4D4F8E12924291ECE89A.1.6.1.20231122.a973bf2.pbiviz.zip)

**Comment by PBI-David** [comment]
Hi @dm-p  - this works perfectly in my tests. Great work and thanks very much for fixing 🎉. 

I have one suggestion which is not material. Have you considered persisting the rows per page value when switching between datasets? Not a big deal but thought it may be worth raising. 

![image](https://github.com/deneb-viz/deneb/assets/86846675/492e6a6f-3d75-41cb-8215-a936fe370dad)

**Comment by dm-p** [comment]
I've submitted 1.6.2, which contains hotfixes deemed too critical to wait until 1.7 (including this one). I'll update you further once this has been approved.
