### ISSUE TITLE
Persist Rows Per Page Value

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#398]
Persist the rows per page value when switching between datasets as described in https://github.com/deneb-viz/deneb/issues/391#issuecomment-1822395773

![image](https://github.com/deneb-viz/deneb/assets/86846675/a424ee63-3f40-4552-ab3d-314c66c04709)

Maybe even persist between sessions as a config option.

**Comment by dm-p** [comment]
The following changes are present in the latest 1.7 alpha build:

- Default rows per page value is now **50**.
- Rows per page options extended to include **150** and **200** as options.
- The rows per page value is persisted to a new property called **# of rows per table page** in the new **Editor > Debug pane** formatting card. This is bidirectional in that changing one affects the other, e.g.:

https://github.com/deneb-viz/deneb/assets/10572054/c2fa1a81-a421-47e8-9f2d-8fb4dba2109a

The video should also demonstrate that changing the pane or dataset retains the setting.

Note that 1.7 is quite far from being ready to submit for release, but I'm trying to keep things closer to the trunk for planned changes for a release rather than drop a whole bunch of stuff all at once. Hopefully, this approach will help you verify features and provide feedback earlier.

If you can test with the latest alpha build, you can close the issue if it passes, and I'll include it in 1.7 when it is ready to submit.

**Comment by PBI-David** [comment]
Thanks Daniel. Functionality works and I'm happy to close. FYI. there is a bug in the pagination _display_ logic. To recreate:

1.  Page to the end using the editor

![image](https://github.com/deneb-viz/deneb/assets/86846675/360a0a3e-8615-402d-977d-69d759fd815b)

2. Use the debug pane to set a higher pagination (in this case from 10 to 200). 

![image](https://github.com/deneb-viz/deneb/assets/86846675/0c8ffea4-d4fa-4bcc-8d74-b782e1f41c4e)

Notice the pagination calcs are now off (4401-4600 off 221)


There was another bug where I could page past 50 but I can't reliably recreate it and I suspect it has the same root cause as the one above anyway.

**Comment by dm-p** [comment]
Thanks for confirming that it works👍

Regarding the follow-up issue, I was able to repro and have submitted a fix, which will be in the next alpha build. Thanks for finding that one, too!

**Comment by dm-p** [comment]
As a heads-up, I've had an issue with 1.6.1 that has caused me to delay 1.6.2, so these changes will be part of that submission as they are now part of the trunk. I'm awaiting confirmation on the 1.6.1 issue being resolved and will then re-submit 1.6.2 with these additional changes.
