### ISSUE TITLE
Tooltip rendering stopped working in latest version

### ISSUE THREAD

**Issue by dniedrauer** [deneb-viz/deneb#407]
After the latest update to Deneb, I am having issues with tooltip rendering within power bi. 

Below is the relevant portion of my code. 

  "signals": [
    {
      "name": "tooltip",
      "value": {},
      "on": [
        {"events": "symbol:mouseover", "update": "datum"},
        {"events": "symbol:mouseout", "update": "{}"}
      ]
    }
  ],

 },
        "hover": {
          "opacity": {"value": 0.5},
          "tooltip": {
            "signal": "{'location': datum['location'], 'value': datum['value']}"
          }
        }
      }
    },
    
    As a temporary workaround, going to Deneb>Settings>Power BI interactivity and unchecking "Tooltip handler" brings back tooltip functionality.

**Comment by dm-p** [comment]
I had someone flag this to me privately yesterday, and I'm currently working with Microsoft to see if they can resolve the issue for the published AppSource version. I haven't had a chance to create an issue for it, so I appreciate you doing so.

To try to attack both sides, I have submitted an update that works around the issue (and has been verified as working by the person who initially raised it). This will display Power BI tooltips correctly. 

Given the normal approval process and time of year (where MS has a reduced support capacity due to holidays), I don't have an ETA for when this will go live. I usually only make the standalone version available once submission/certification is complete, but given the severity of the issue, I have decided to make this available earlier. [You can download this here](https://github.com/deneb-viz/deneb/releases/tag/1.6.1.2).

For those who have to use the AppSource version, you can work around the issue (as @dniedrauer has provided) by falling back to the Vega tooltip handler inside Deneb by switching off the tooltip handler in the settings. Note that this will not work for those wanting to display report page tooltips.

**Comment by jeanny-z8** [comment]
Thanks for this. Look forward to MS approving v1.6.2, but will use the standalone where needed in the meantime.

**Comment by dm-p** [comment]
1.6.2 has been approved by MS for certification, so this should get to production as soon as the deployment process allows. Due to the holiday period, MS has indicated that this may be slightly longer than usual, but they're doing their best to help get this through.

1.6.2 also contains some other minor changes and bug fixes - the details of these are documented in the [Change Log](https://deneb-viz.github.io/changelog).

**Comment by michal-ozimek** [comment]
Tooltips which have worked in the past are still not working in 1.6.2, neither version you've linked, nor AppSource (it seems approved by MS now). I'm trying to display report page tooltips.

**Comment by dm-p** [comment]
1.6.2 is deployed in my region (which is usually the last to get production changes), so I'm closing this as complete.
