### ISSUE TITLE
enhancement: add scrollTop and scrollLeft as standard signals

### ISSUE THREAD

**Issue by Giammaria** [deneb-viz/deneb#431]
Request to have [Element.scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) and [Element.scrollLeft](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) added to the list of default signal values that are made available in Deneb. This will allow for the repositioning of marks based on scroll position.

**Comment by dm-p** [comment]
I'll take a look. Given that these aren't Vega-specific signals, I have two suggestions:

1. Add individual `pbiContainerScrollTop` and `pbiContainerScrollLeft` signals as numeric values.
    * This is simpler but will increase the cardinality of available signals by default.

2. Add a `pbiContainer` signal, which is an object containing relevant properties.
    * To start with, we can add `pbiContainer.scrollTop` and `pbiContainer.scrollLeft`.
    * We could extend this later with other options without adding too many individual signals.
    * This doesn't solve the problem of the `pbiContainerHeight` and `pbiContainerWidth` signals we patch in for Vega specifications, so we'll probably leave them in for legacy reasons (but maybe we'll add `height` and `width` properties with the same values as the signals.
    * At some point, we might be able to add a migration step to find/replace any instances of the legacy signals and replace them with `pbiContainer.height` and `pbiContainer.width` accordingly.

Which makes the most sense for you as a developer?

**Comment by Giammaria** [comment]
I am happy with either approach. I'm not married to any naming convention, and am perfectly fine with these values being attributes on a single object. As with most things, I'll defer to your judgement 😃. As long as the values are accessible, I can adapt.

**Comment by Giammaria** [comment]
@dm-p, could this be a last minute candidate for 1.7 #434, or am I oversimplifying the LOE for this?

**Comment by dm-p** [comment]
@Giammaria - I can size it to see if I can get it to work. Would your request include updating the signal values in the view as the user scrolls in Power BI? If so, this adds to the complexity a bit, as we'll need to add support for this (which I was going to do as part of #410).

If you can confirm, I'll see what might be possible, but as 1.7 is already huge I don't want to delay it longer than it already has been if I can help it.

**Comment by Giammaria** [comment]
Hi @dm-p, yes the ask would be to have those values update anytime the scroll position changes within Deneb's visual sandbox. I completely understand if this is too much to put into 1.7.

**Comment by dm-p** [comment]
I had a quick look at patching in something and binding an event listener to the scrollbars if they're present. Did a short test by encoding a sequential number table along the y-axis and then binding a single mark to the signal value. Looks promising :)

https://github.com/deneb-viz/deneb/assets/10572054/c56f15bc-d3f1-4aa6-bf5b-f8f413cbb798

This is without strategy, but it looks workable. As the view doesn't let us create signals (just update them), we will need to:

- Patch in the signal + initial values when we generate/parse the spec
- Add typings and API for the object structure (to make it extensible)
- Update our view services to manage this gracefully
- Finesse the signal viewer's state setter/getters
- Update the container's scroll event to update the view's signals with the new values
- (possibly) add the ability to debounce or throttle the frequency of this via a property (maybe 0ms - 200ms), in case scrolling + the signal updates affect the performance of the view (although this example was OK for 1K marks)
- Add a listener for the container width/height, and update the signal in a similar manner (probably respecting the same debounce/throttle if we add that)

I think that might be it. I'll see how the remaining issues for 1.7 go before I start alpha testing, and if things go well, I'll try and squeeze this in, otherwise it'll have to be 1.8. I'll keep on the backlog for now and allocate a correct target release soon.

**Comment by PBI-David** [comment]
I'm sure there won't be a problem but can you try positioning your mark with a negative y value just in case.

**Comment by dm-p** [comment]
Numbers will always be positive (or zero) as they come from the containing element and these are set by the browser. I did try setting it to negative (scrollHeight - 20) before recording the video and it's effectively the same as setting an explicit negative value (pushes the view downward and positions the mark within the canvas, but above)

**Comment by Giammaria** [comment]
This looks excellent!

**Comment by dm-p** [comment]
This is in the latest alpha build and available for you to test with. I'm planning to update the documentation site in more detail as part of the release process, but in the meantime I think that everything you need to get started should be on the [1.7 change log page (under `pbiContainer` Signal)](https://deneb-viz.github.io/next/changelog#pbicontainer-signal).

Note that I've also added `scrollWidth` and `scrollHeight` to this object in case you need this.

**Comment by Giammaria** [comment]
Thanks Daniel! `scrollWidth `and `scrollHeight `will certainly come in handy!

**Comment by dm-p** [comment]
I'm marking this as done. If anything comes up during 1.7 beta testing, we can re-open it (or create a new issue to track).
