### ISSUE TITLE
v1.7.0 broken on PBI Desktop v2.131.1203.0

### ISSUE THREAD

**Issue by dkcheng** [deneb-viz/deneb#478]
I just received an update to PBI Desktop v2.131.1203.0, released 7/26/2024, and it seems to break Deneb entirely. I am unsure if anybody else is experiencing this, so apologies if a bug report is not appropriate here.

By "break", I mean the following behaviors occur:
1. If I create a new visual and drag a field into its "Values", it disappears despite it showing that it is used ![image](https://github.com/user-attachments/assets/2fef1f7c-e049-4225-a9e2-15eafec656dc)
2. If I then click "edit" on the visual, everything is blanked out
3. If I open up an older .pbix file (pre-PBI Desktop update), all of the visuals disappear

**Comment by dm-p** [comment]
Hi, and thanks for raising. Can you check to see if other visuals are affected? MS has broken custom visuals in Desktop due to a WebView2 update ([as detailed at the Fabric support site](https://support.fabric.microsoft.com/)):

![image](https://github.com/user-attachments/assets/0f3d8fdc-5b6a-4540-a517-4304b6235807)

If this is the case, you may need to downgrade or wait for a new version of Desktop. Visuals will still work in the Power BI Service.

**Comment by dkcheng** [comment]
That must be it. I never thought to check other custom visuals -- Deneb is the _only_ one I use 😄. Some of them are indeed broken. I'll try downgrading WebView2 and seeing if that works. Thank you so much for the quick response, and for all your hard work!
