### ISSUE TITLE
v1.7: Version shows as 1.6.2.1

### ISSUE THREAD

**Issue by vfridkin** [deneb-viz/deneb#479]
Minor thing but got me confused about whether I have the latest version.

![image](https://github.com/user-attachments/assets/a4402a22-3c34-471b-a8b3-984424f57b5f)

**Comment by dm-p** [comment]
Hi there, and thanks for getting in touch. You are still on 1.6 for the moment.

When the visual passes certification, the listing updates immediately. The new version takes approximately 2-3 weeks for MS to roll out across tenants fully, and its timeline is entirely out of our control. That's why we like to do beta testing before submission: while it can be easy to fix a bug, it can take weeks to deploy a fix for people.

Like you, I'm still getting 1.6, but others are getting 1.7 delivered to their reports already. If you don't have it yet, you will likely get it around the end of this week/early next week. But if you get it from AppSource, it will eventually update to 1.7 as MS finishes rolling it out. 

When updated, you can confirm by right-clicking the visual in the Visualizations pane, selecting 'About', or checking the splash screen, as you have done here (as we update the version on display from the visual manifest shared by the Visualizations pane. The about dialog also confirms where you are sourcing from, e.g.:

![image](https://github.com/user-attachments/assets/29ef4297-e244-4dc6-a259-dc98b2a86d0e)

For existing visuals, you will also get a notification when you next open the advanced editor (visual header >Edit)
