### ISSUE TITLE
gantt chart shows date that is -1 from actual data 

### ISSUE THREAD

**Issue by jac1314** [deneb-viz/deneb#482]
Hi, I'm not sure if my settings are accurate. I'm in PST time zone and did not modify the data or json. The gantt chart shows date that is -1 from actual data. For example, the gantt chart is showing a start date of 31 Mar 24 but the actual table data is showing a start date of 1 Apr 24. Thank you.

![PBIDesktop_E042oKNL9F](https://github.com/user-attachments/assets/5fa6b4b3-5e6f-4fe0-a6ea-f8d643acab93)
![PBIDesktop_s2CYQPQabN](https://github.com/user-attachments/assets/2335c055-ba8e-49dc-9fbf-4f114561a421)

**Comment by PBI-David** [comment]
Questions like this should go on Stack Overflow as they're nothing to do with Deneb. This is a UTC issue and the fix is to ensure you have the very latest code from here: https://github.com/PBI-David/Deneb-Showcase. If you need further help, please make move the discussion to SO and provide your .pbix demonstrating the issue.
