### ISSUE TITLE
Export to PDF 

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#509]
I don't think this has been raised. I have tested and I observe the same behaviour. The pdf export only exports the default view of the visualisation rather than any dynamic changes the user has performed like changing the date granularity. Is this a known limitation or something that can be resolved? Possibly related to https://github.com/deneb-viz/deneb/issues/410?

https://old.reddit.com/r/PowerBI/comments/122o5ko/gantt_charts_in_power_bi/lrqi2wd/?context=3

> 
>  This Gantt Chart is really useful in visually presenting once projects. Its of great help.
> I just have one issue in exporting the chart to PDF. It does not export the current visual that I select and by default exports only Days view even if I select Months or Year. Anything that I need to take care in the code ?

**Comment by dm-p** [comment]
When you export to PDF, Power BI will open all pages sequentially in their initial state. In Desktop, you will sometimes see this cycle through while you export. In the Service, your report is opened "somewhere else" and done server-side rather than client-side while this is going on. We learned this during the 1.7 rollout, where folks had already started adding specifications containing comments, and the version of Deneb on the remote location hadn't yet been updated and was failing to export.

Either way, due to the way the report is opened/cycled in a completely separate process, the workbook is essentially opened in a completely different viewing session, and all visuals on a page will be included in their **initial** state, not their last displayed state.

For Deneb, you would need to set the initial signal value accordingly for it to export correctly.

**Comment by dm-p** [comment]
It affects all visuals in a report, not just custom visuals. I can raise it, but it's unlikely to get resolved.
