### ISSUE TITLE
Alerts on empty template

### ISSUE THREAD

**Issue by kolky001** [deneb-viz/deneb#51]
Any way to remove the alerts on the empty template so as not to alarm the user upon first opening? 
![image](https://user-images.githubusercontent.com/36867587/120645597-bfbfa800-c4b7-11eb-955b-877ec5c2f0c5.png)

<img width="272" alt="alert" src="https://user-images.githubusercontent.com/36867587/120646737-f8ac4c80-c4b8-11eb-9c16-f3707b7c6b0a.PNG">

**Comment by dm-p** [comment]
Ideally I'd like to use Monaco (the VS Code editor that the Vega editor uses, as this is a lot more subtle with JSON schema validation errors, but I've tried several times to make it work and there's some architecture issues with custom visuals where I need to get Monaco's workers loaded for code highlighting and schema validation, and I've spent heaps of time on this already to no avail (although I'm sure I'll manage it one day).

I've had a think about this for now and it might be tricky to resolve gracefully without hackery. We _might_ be able to disable schema validation _if_ the spec content is exactly the same as the Vega-Lite blank template and then re-enable it as soon as it differs.

What would you expect to see here? I'm open to suggestions!

**Comment by dm-p** [comment]
I think that the only way to make this work within the framework  (and given that everyone's datasets are likely to result in a varying quantity of marks) would be to replace the template with:

```json
{
  "data": {"name": "dataset"},
  "layer": []
}
```

I propose that we do this in 1.3, so that the dataset viewer etc. doesn't add to the level of alarm for new users, i.e.:

![image](https://user-images.githubusercontent.com/10572054/168497177-4150c050-da1c-4313-b405-aff5d7462a3c.png)

Instead of:

![image](https://user-images.githubusercontent.com/10572054/168497200-523d912c-3d82-4aa9-be40-b7ad79aa621f.png)

Please feel free to suggest an alternative if you don't think this suits.

**Comment by kolky001** [comment]
I initially thought the "layer":[ ] might confuse, but now thinking about it, I think it will be fine
