### ISSUE TITLE
Edit Field Mapping appears on each edit

### ISSUE THREAD

**Issue by maxanatsko** [deneb-viz/deneb#511]
Hi,
Version: 1.7.2.1 from AppSource.

**Empty** Edit specification field mapping window appears after **each** spec edit. Auto-apply changes is **off**.

<img width="1696" alt="Screenshot 2024-10-19 162915" src="https://github.com/user-attachments/assets/ebdecd2e-5211-45e2-9664-67f41389cec7">

**Comment by dm-p** [comment]
Hi and thanks for reporting - it looks like something in the spec may be tripping up up the tracking/mapping algorithm. For the moment you may be able to "reset" it so you can continue working by re-initializing the visual instance (navigate away from the current report page and back to the visual so that Power BI reloads everything correctly).

Do you have a workbook/spec and steps that can reproduce the issue? This would be a great help in me being able to see this happening myself, isolate the root cause and hopefully make a fix.

**Comment by Giammaria** [comment]
#486

**Comment by dm-p** [comment]
OK I'll use #486 as the basis for investigation - apologies, I must have just seen the feature request portion and parked it for a time where I could plan it out. @maxanatsko - if you have any further context, please add there.

**Comment by Giammaria** [comment]
Hey, no problem @dm-p! I really just mentioned #486 so the discussions could be referenced across issues, and maybe ultimately be consolidated.
