### ISSUE TITLE
Working with Dynamic Format Strings (for Measures and Calculation Groups)

### ISSUE THREAD

**Issue by Klimkiv** [deneb-viz/deneb#517]
Daniel, good day!

I've read article [Working with Dynamic Format Strings (for Measures and Calculation Groups)] many times but can't understand how to use [measure_name]__formatted
We've got
![image](https://github.com/user-attachments/assets/2f65625a-7b40-4218-9243-1c0b6c6c2026)

and if we use formatted field like
![image](https://github.com/user-attachments/assets/a4201351-64e7-4909-9a9b-2319b782a857)

we get
![image](https://github.com/user-attachments/assets/53685a46-40b7-47d3-9beb-4489903acdc6)
 
it's perfect!

but how to use the same formatted field to axis labels? We try something like that with labelExpr but no result

![image](https://github.com/user-attachments/assets/20262ae4-d1cb-4501-a22c-2ab03e370c09)

Please add 2-3 sentences about proper using formatted fields to axis labels

**Comment by dm-p** [comment]
Hi there—because axes are algorithmically generated, they are not tied to rows in the dataset. The `datum` object available is whatever Vega has resolved the current label based on the axis type. For `quantitative` scales, these will not correlate 1:1 with the granularity of your data, so you can't just access a row how you expect (I've been there also).

I don't think solving this is 2-3 sentences, but the simplest approach I can think of would be to identify a row in your dataset that contains the desired format string, store that in a signal (`param`), and feed that into a `labelExpr`.

This is a bad example, but it's all I have on hand right now. Let's start with this dataset:

![image](https://github.com/user-attachments/assets/b21559aa-216f-4f95-a2db-1fb664904119)

And my spec looks like this:

```json
{
  "data": { "name": "dataset" },
  "layer": [
    {
      "mark": { "type": "bar" }
    },
    {
      "mark": {
        "type": "text",
        "align": "left",
        "dx": 5
      },
      "encoding": {
        "text": {"field": "$ Sales__formatted" }
      }
    }
  ],
  "encoding": {
    "x": {
      "field": "$ Sales",
      "type": "quantitative"
    },
    "y": {
      "field": "Sales CG",
      "type": "nominal"
    }
  }
}
```

![image](https://github.com/user-attachments/assets/9f72139b-0127-4035-93f0-e89c3199770d)

----

While all the format strings are the same, let's assume that the one in the first row is the one I want to use on the axis. I can do this by adding a param, like this:

```json
{
  ...
  "params": [
    {
      "name": "axis_format",
      "expr": "pluck(data('dataset'), '$ Sales__format')[0]"
    }
  ],
  ...
}
```

Here, I'm chaining the `pluck` and `data` functions ([ref: Expressions](https://vega.github.io/vega/docs/expressions/)) to get all values of the `$ Sales__format` column from the named Deneb `dataset`, and then access the first entry (`[0]`).

In the _Signals_ Pane, we should now see a corresponding value, e.g.:

![image](https://github.com/user-attachments/assets/6b322871-97f1-46f5-8d3c-61a884c64224)

I can then use this derived value in a `labelExpr` in my axis as follows:

```json
{
  ...
  "encoding": {
    "x": {
      "field": "$ Sales",
      "type": "quantitative",
      "axis": {
        "labelExpr": "pbiFormat(datum.value, axis_format)"
      }
    },
    ...
  }
}
```

This would now apply to my axis, e.g.:

![image](https://github.com/user-attachments/assets/9c659763-9f3a-4591-8095-077fc8bdb572)

----

Hopefully, an approach like this will help you solve your challenge. Good luck!

**Comment by Klimkiv** [comment]
Daniel, good day and thank you very much!

1. with your help I get to know how to return legend title as a variable, if we should show on a visual just one distinct value from some category field from dataset ( through slicer for example) we can  write 
  "signals": [
    {
      "name": "test",
      "update": "slice(pluck(data('dataset'),'Category'),0,1)"
    }
and use it in a legend like "title": { "signal": "test" } to get 
![image](https://github.com/user-attachments/assets/cafc81e3-d7b9-4d48-a64f-93c1cce218a2)

and if select another category item we get
![image](https://github.com/user-attachments/assets/6313714d-2b48-4d37-9d6e-79e3d61c79db)

so thank you very much

2. and we can format legend labels the same way
![image](https://github.com/user-attachments/assets/fb665cd5-7abf-4dd8-b736-1220d741fe85)

**Comment by dm-p** [comment]
Glad I could help! For now, this approach will help solve this particular use case (and I use this a lot in my projects, too). As this works for you, I'll close the issue as resolved 👍
