### ISSUE TITLE
Persisting Selected Pattern for Each Discipline in Deneb Visual with Vega-Lite in Power BI

### ISSUE THREAD

**Issue by adarshthouti** [deneb-viz/deneb#519]
Hi All, 

I am working on a Deneb visual in Power BI using the Vega-Lite provider, and I need help with implementing a way to apply and persist changes made to the selected discipline and its associated pattern.

Current Setup:

1. I have a JSON configuration in my Deneb visual that includes:
     a) Dropdowns for selecting patterns for different disciplines (e.g., "Discipline 1", "Discipline 2", "Discipline 3").
     b) An "Apply" button to confirm the selection.
2.  The patterns (e.g., "red", "blue", "diagonal-stripe-3") are applied dynamically based on user input using parameters.
3. I also have slicers in Power BI to filter by discipline.

Issue:
When I use the slicer to select a discipline, the Deneb visual resets the applied pattern and doesn’t retain the previously selected values. I want the visual to:

1. Persist the selected patterns even after filtering via slicers.
2. Allow the user to click "Apply" to confirm changes, ensuring they are maintained until explicitly modified.

![LS8](https://github.com/user-attachments/assets/0e7ff765-cc20-43dc-8f5f-8c1817c8dc14)

**Comment by dm-p** [comment]
Transferring to correct repo

**Comment by dm-p** [comment]
As you have identified, parameters 'reset' when events on the canvas happen. This is due to how Power BI sends data to visuals and updates them when these events occur. 

I have a mitigation for this planned in #410, where parameters will be 'durable' for the complete lifecycle of a visual instance, that is one of the following:

1. (If viewing a visual) from when a visual is initialized on the canvas to when it is destroyed (either through leaving the page, hiding it via a bookmark, or exiting the report).
2. (If editing the visual), each time a change to the underlying JSON is applied (as this requires a recompile).

This requires significant work to Deneb's architecture to retain the state for a signal for the current viewing session, which will be implemented in v2. There is no ETA for this, but it is expected to be sometime next year.

As such, I'll close this as a duplicate, as #410 is tracking this work. You are welcome to monitor that issue and add requirements to it, or if I have misunderstood, you can reopen this issue with more information to help flesh out the use case you need.
